package de.regatta_hd.aquarius.db.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "AgeClass")
@IdClass(de.regatta_hd.aquarius.db.model.AgeClassId.class)
public class AgeClass {
	@Basic
	@Column(name = "AgeClass_Abbr", nullable = false, length = 8)
	private String ageClassAbbr;

	@Basic
	@Column(name = "AgeClass_AbbrSuffix", length = 8)
	private String ageClassAbbrSuffix;

	@Basic
	@Column(name = "AgeClass_AllowYounger")
	private byte ageClassAllowYounger;

	@Basic
	@Column(name = "AgeClass_Caption", nullable = false, length = 48)
	private String ageClassCaption;

	@Basic
	@Column(name = "AgeClass_Gender", nullable = false, length = 1)
	private String ageClassGender;

	@Id
	@Column(name = "AgeClass_ID", columnDefinition = "int identity")
	private int ageClassID;

	@Basic
	@Column(name = "AgeClass_LW_AvgLimit")
	private Integer ageClassLWAvgLimit;

	@Basic
	@Column(name = "AgeClass_LW_CoxLowerLimit")
	private Integer ageClassLWCoxLowerLimit;

	@Basic
	@Column(name = "AgeClass_LW_CoxTolerance")
	private Integer ageClassLWCoxTolerance;

	@Basic
	@Column(name = "AgeClass_LW_UpperLimit")
	private Integer ageClassLWUpperLimit;

	@Basic
	@Column(name = "AgeClass_MaxAge")
	private byte ageClassMaxAge;

	@Basic
	@Column(name = "AgeClass_MinAge")
	private byte ageClassMinAge;

	@Basic
	@Column(name = "AgeClass_NumSubClasses")
	private byte ageClassNumSubClasses;

	@Basic
	@Column(name = "AgeClass_Suffix", length = 16)
	private String ageClassSuffix;

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.Offer.class, mappedBy = "ageClass", cascade = CascadeType.MERGE)
	private Set<Offer> offers = new HashSet<>();

	public AgeClass() {
	}

	public AgeClass(int ageClassID) {
		this.ageClassID = ageClassID;
	}

	public String getAgeClassAbbr() {
		return this.ageClassAbbr;
	}

	public void setAgeClassAbbr(String ageClassAbbr) {
		this.ageClassAbbr = ageClassAbbr;
	}

	public String getAgeClassAbbrSuffix() {
		return this.ageClassAbbrSuffix;
	}

	public void setAgeClassAbbrSuffix(String ageClassAbbrSuffix) {
		this.ageClassAbbrSuffix = ageClassAbbrSuffix;
	}

	public byte getAgeClassAllowYounger() {
		return this.ageClassAllowYounger;
	}

	public void setAgeClassAllowYounger(byte ageClassAllowYounger) {
		this.ageClassAllowYounger = ageClassAllowYounger;
	}

	public String getAgeClassCaption() {
		return this.ageClassCaption;
	}

	public void setAgeClassCaption(String ageClassCaption) {
		this.ageClassCaption = ageClassCaption;
	}

	public String getAgeClassGender() {
		return this.ageClassGender;
	}

	public void setAgeClassGender(String ageClassGender) {
		this.ageClassGender = ageClassGender;
	}

	public int getAgeClassID() {
		return this.ageClassID;
	}

	public void setAgeClassID(int ageClassID) {
		this.ageClassID = ageClassID;
	}

	public Integer getAgeClassLWAvgLimit() {
		return this.ageClassLWAvgLimit;
	}

	public void setAgeClassLWAvgLimit(Integer ageClassLWAvgLimit) {
		this.ageClassLWAvgLimit = ageClassLWAvgLimit;
	}

	public Integer getAgeClassLWCoxLowerLimit() {
		return this.ageClassLWCoxLowerLimit;
	}

	public void setAgeClassLWCoxLowerLimit(Integer ageClassLWCoxLowerLimit) {
		this.ageClassLWCoxLowerLimit = ageClassLWCoxLowerLimit;
	}

	public Integer getAgeClassLWCoxTolerance() {
		return this.ageClassLWCoxTolerance;
	}

	public void setAgeClassLWCoxTolerance(Integer ageClassLWCoxTolerance) {
		this.ageClassLWCoxTolerance = ageClassLWCoxTolerance;
	}

	public Integer getAgeClassLWUpperLimit() {
		return this.ageClassLWUpperLimit;
	}

	public void setAgeClassLWUpperLimit(Integer ageClassLWUpperLimit) {
		this.ageClassLWUpperLimit = ageClassLWUpperLimit;
	}

	public byte getAgeClassMaxAge() {
		return this.ageClassMaxAge;
	}

	public void setAgeClassMaxAge(byte ageClassMaxAge) {
		this.ageClassMaxAge = ageClassMaxAge;
	}

	public byte getAgeClassMinAge() {
		return this.ageClassMinAge;
	}

	public void setAgeClassMinAge(byte ageClassMinAge) {
		this.ageClassMinAge = ageClassMinAge;
	}

	public byte getAgeClassNumSubClasses() {
		return this.ageClassNumSubClasses;
	}

	public void setAgeClassNumSubClasses(byte ageClassNumSubClasses) {
		this.ageClassNumSubClasses = ageClassNumSubClasses;
	}

	public String getAgeClassSuffix() {
		return this.ageClassSuffix;
	}

	public void setAgeClassSuffix(String ageClassSuffix) {
		this.ageClassSuffix = ageClassSuffix;
	}

	public Set<Offer> getOffers() {
		return this.offers;
	}

	public void setOffers(Set<Offer> offers) {
		this.offers = offers;
	}
}