package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.AgeClass
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class AgeClassId implements Serializable {

	private static final long serialVersionUID = 1233243545357371389L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.AgeClass");
		} catch (Exception e) {
		}
	}

	public int ageClassID;

	public AgeClassId() {
	}

	public AgeClassId(String str) {
		fromString(str);
	}

	public int getAgeClassID() {
		return this.ageClassID;
	}

	public void setAgeClassID(int ageClassID) {
		this.ageClassID = ageClassID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.ageClassID);
	}

	@Override
	public int hashCode() {
		return this.ageClassID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		AgeClassId other = (AgeClassId) obj;
		return (this.ageClassID == other.ageClassID);
	}

	private void fromString(String str) {
		this.ageClassID = Integer.parseInt(str);
	}
}