package de.regatta_hd.aquarius.db.model;

import jakarta.persistence.Basic;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.Date;
import java.util.List;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "Athlet")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true, doNotUseGetters = true)
public class Athlet {
	@Basic
	@Column(name = "Athlet_DOB", columnDefinition = "datetime", nullable = false)
	private Date dob;

	@Basic
	@Column(name = "Athlet_ExternID_A", length = 11)
	private String externIDA;

	@Basic
	@Column(name = "Athlet_ExternID_B", length = 11)
	private String externIDB;

	@Basic
	@Column(name = "Athlet_ExternState")
	private Byte externState;

	@Basic
	@Column(name = "Athlet_ExternState_B")
	private Byte externStateB;

	@Basic
	@Column(name = "Athlet_FirstName", nullable = false, length = 32)
	@ToString.Include(rank = 9)
	private String firstName;

	@Basic
	@Column(name = "Athlet_Gender", nullable = false, length = 1)
	@ToString.Include(rank = 8)
	private String gender;

	@Id
	@Column(name = "Athlet_ID", columnDefinition = "int identity")
	private int id;

	@Basic
	@Column(name = "Athlet_LastName", nullable = false, length = 64)
	@ToString.Include(rank = 10)
	private String lastName;

	@Basic
	@Column(name = "Athlet_SoundEx", length = 5)
	private String soundEx;

	@Basic
	@Column(name = "Athlet_State")
	private byte state;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Athlet_Club_ID_FK")
	@ToString.Include(rank = 2)
	private Club club;

	@OneToMany(targetEntity = Crew.class, mappedBy = "athlet", cascade = CascadeType.MERGE)
	private List<Crew> crews;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Athlet_Nation_ID_FK")
	@ToString.Include(rank = 1)
	private Nation nation;
}