package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Athlet
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class AthletId implements Serializable {

	private static final long serialVersionUID = -2168123296065350794L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Athlet");
		} catch (Exception e) {
		}
	}

	public int athletID;

	public AthletId() {
	}

	public AthletId(String str) {
		fromString(str);
	}

	public int getAthletID() {
		return this.athletID;
	}

	public void setAthletID(int athletID) {
		this.athletID = athletID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.athletID);
	}

	@Override
	public int hashCode() {
		return this.athletID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		AthletId other = (AthletId) obj;
		return (this.athletID == other.athletID);
	}

	private void fromString(String str) {
		this.athletID = Integer.parseInt(str);
	}
}