package de.regatta_hd.aquarius.db.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "Athlet")
@IdClass(de.regatta_hd.aquarius.db.model.AthletId.class)
public class Athlet {
	@Basic
	@Column(name = "Athlet_DOB", columnDefinition = "datetime", nullable = false)
	private Date athletDOB;

	@Basic
	@Column(name = "Athlet_ExternID_A", length = 11)
	private String athletExternIDA;

	@Basic
	@Column(name = "Athlet_ExternID_B", length = 11)
	private String athletExternIDB;

	@Basic
	@Column(name = "Athlet_ExternState")
	private Byte athletExternState;

	@Basic
	@Column(name = "Athlet_ExternState_B")
	private Byte athletExternStateB;

	@Basic
	@Column(name = "Athlet_FirstName", nullable = false, length = 32)
	private String athletFirstName;

	@Basic
	@Column(name = "Athlet_Gender", nullable = false, length = 1)
	private String athletGender;

	@Id
	@Column(name = "Athlet_ID", columnDefinition = "int identity")
	private int athletID;

	@Basic
	@Column(name = "Athlet_LastName", nullable = false, length = 64)
	private String athletLastName;

	@Basic
	@Column(name = "Athlet_SoundEx", length = 5)
	private String athletSoundEx;

	@Basic
	@Column(name = "Athlet_State")
	private byte athletState;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Athlet_Club_ID_FK")
	private Club club;

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.Crew.class, mappedBy = "athlet", cascade = CascadeType.MERGE)
	private Set<Crew> crews = new HashSet<>();

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Athlet_Nation_ID_FK")
	private Nation nation;

	public Athlet() {
	}

	public Athlet(int athletID) {
		this.athletID = athletID;
	}

	public Date getAthletDOB() {
		return this.athletDOB;
	}

	public void setAthletDOB(Date athletDOB) {
		this.athletDOB = athletDOB;
	}

	public String getAthletExternIDA() {
		return this.athletExternIDA;
	}

	public void setAthletExternIDA(String athletExternIDA) {
		this.athletExternIDA = athletExternIDA;
	}

	public String getAthletExternIDB() {
		return this.athletExternIDB;
	}

	public void setAthletExternIDB(String athletExternIDB) {
		this.athletExternIDB = athletExternIDB;
	}

	public Byte getAthletExternState() {
		return this.athletExternState;
	}

	public void setAthletExternState(Byte athletExternState) {
		this.athletExternState = athletExternState;
	}

	public Byte getAthletExternStateB() {
		return this.athletExternStateB;
	}

	public void setAthletExternStateB(Byte athletExternStateB) {
		this.athletExternStateB = athletExternStateB;
	}

	public String getAthletFirstName() {
		return this.athletFirstName;
	}

	public void setAthletFirstName(String athletFirstName) {
		this.athletFirstName = athletFirstName;
	}

	public String getAthletGender() {
		return this.athletGender;
	}

	public void setAthletGender(String athletGender) {
		this.athletGender = athletGender;
	}

	public int getAthletID() {
		return this.athletID;
	}

	public void setAthletID(int athletID) {
		this.athletID = athletID;
	}

	public String getAthletLastName() {
		return this.athletLastName;
	}

	public void setAthletLastName(String athletLastName) {
		this.athletLastName = athletLastName;
	}

	public String getAthletSoundEx() {
		return this.athletSoundEx;
	}

	public void setAthletSoundEx(String athletSoundEx) {
		this.athletSoundEx = athletSoundEx;
	}

	public byte getAthletState() {
		return this.athletState;
	}

	public void setAthletState(byte athletState) {
		this.athletState = athletState;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public Set<Crew> getCrews() {
		return this.crews;
	}

	public void setCrews(Set<Crew> crews) {
		this.crews = crews;
	}

	public Nation getNation() {
		return this.nation;
	}

	public void setNation(Nation nation) {
		this.nation = nation;
	}
}