package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.BoatClass
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class BoatClassId implements Serializable {

	private static final long serialVersionUID = -5150690217119318398L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.BoatClass");
		} catch (Exception e) {
		}
	}

	public int boatClassID;

	public BoatClassId() {
	}

	public BoatClassId(String str) {
		fromString(str);
	}

	public int getBoatClassID() {
		return this.boatClassID;
	}

	public void setBoatClassID(int boatClassID) {
		this.boatClassID = boatClassID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.boatClassID);
	}

	@Override
	public int hashCode() {
		return this.boatClassID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		BoatClassId other = (BoatClassId) obj;
		return (this.boatClassID == other.boatClassID);
	}

	private void fromString(String str) {
		this.boatClassID = Integer.parseInt(str);
	}
}