package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Club
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class ClubId implements Serializable {

	private static final long serialVersionUID = -5642805298325759636L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Club");
		} catch (Exception e) {
		}
	}

	public int clubID;

	public ClubId() {
	}

	public ClubId(String str) {
		fromString(str);
	}

	public int getClubID() {
		return this.clubID;
	}

	public void setClubID(int clubID) {
		this.clubID = clubID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.clubID);
	}

	@Override
	public int hashCode() {
		return this.clubID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		ClubId other = (ClubId) obj;
		return (this.clubID == other.clubID);
	}

	private void fromString(String str) {
		this.clubID = Integer.parseInt(str);
	}
}