package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

import lombok.Data;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Club
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
@Data
public class ClubId implements Serializable {

	private static final long serialVersionUID = -5642805298325759636L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Club");
		} catch (ClassNotFoundException e) {
		}
	}

	private int id;
}