package de.regatta_hd.aquarius.db.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "CompEntries")
@IdClass(de.regatta_hd.aquarius.db.model.CompEntriesId.class)
public class CompEntries {
	@Basic
	@Column(name = "CE_Lane")
	private Short cELane;

	@Id
	@Column(name = "CE_ID", columnDefinition = "int identity")
	private int ceId;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "CE_Comp_ID_FK")
	private Comp comp;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "CE_Entry_ID_FK", nullable = false)
	private Entry entry;

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.Result.class, mappedBy = "compEntries", cascade = CascadeType.MERGE)
	private Set<Result> results = new HashSet<>();

	public CompEntries() {
	}

	public CompEntries(int ceId) {
		this.ceId = ceId;
	}

	public Short getcELane() {
		return this.cELane;
	}

	public void setcELane(Short cELane) {
		this.cELane = cELane;
	}

	public int getCeId() {
		return this.ceId;
	}

	public void setCeId(int ceId) {
		this.ceId = ceId;
	}

	public Comp getComp() {
		return this.comp;
	}

	public void setComp(Comp comp) {
		this.comp = comp;
	}

	public Entry getEntry() {
		return this.entry;
	}

	public void setEntry(Entry entry) {
		this.entry = entry;
	}

	public Set<Result> getResults() {
		return this.results;
	}

	public void setResults(Set<Result> results) {
		this.results = results;
	}
}