package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.CompEntries
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CompEntriesId implements Serializable {

	private static final long serialVersionUID = 5408116574284706361L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.CompEntries");
		} catch (Exception e) {
		}
	}

	public int ceId;

	public CompEntriesId() {
	}

	public CompEntriesId(String str) {
		fromString(str);
	}

	public int getCeId() {
		return this.ceId;
	}

	public void setCeId(int ceId) {
		this.ceId = ceId;
	}

	@Override
	public String toString() {
		return String.valueOf(this.ceId);
	}

	@Override
	public int hashCode() {
		return this.ceId;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		CompEntriesId other = (CompEntriesId) obj;
		return (this.ceId == other.ceId);
	}

	private void fromString(String str) {
		this.ceId = Integer.parseInt(str);
	}
}