package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

import lombok.Data;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.CompEntries
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
@Data
public class CompEntriesId implements Serializable {

	private static final long serialVersionUID = 5408116574284706361L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.CompEntries");
		} catch (ClassNotFoundException e) {
			throw new IllegalStateException(e);
		}
	}

	public int id;
}