package de.regatta_hd.aquarius.db.model;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "CompReferee")
@IdClass(de.regatta_hd.aquarius.db.model.CompRefereeId.class)
public class CompReferee {
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "CompReferee_Comp_ID_FK", nullable = false)
	private Comp comp;

	@Id
	@Column(name = "CompReferee_ID", columnDefinition = "int identity")
	private int compRefereeID;

	@Basic
	@Column(name = "CompReferee_Role", length = 1)
	private String compRefereeRole;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "CompReferee_Referee_ID_FK", nullable = false)
	private Referee referee;

	public CompReferee() {
	}

	public CompReferee(int compRefereeID) {
		this.compRefereeID = compRefereeID;
	}

	public Comp getComp() {
		return this.comp;
	}

	public void setComp(Comp comp) {
		this.comp = comp;
	}

	public int getCompRefereeID() {
		return this.compRefereeID;
	}

	public void setCompRefereeID(int compRefereeID) {
		this.compRefereeID = compRefereeID;
	}

	public String getCompRefereeRole() {
		return this.compRefereeRole;
	}

	public void setCompRefereeRole(String compRefereeRole) {
		this.compRefereeRole = compRefereeRole;
	}

	public Referee getReferee() {
		return this.referee;
	}

	public void setReferee(Referee referee) {
		this.referee = referee;
	}
}