package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.CompReferee
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CompRefereeId implements Serializable {

	private static final long serialVersionUID = 9138955585742624852L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.CompReferee");
		} catch (Exception e) {
		}
	}

	public int compRefereeID;

	public CompRefereeId() {
	}

	public CompRefereeId(String str) {
		fromString(str);
	}

	public int getCompRefereeID() {
		return this.compRefereeID;
	}

	public void setCompRefereeID(int compRefereeID) {
		this.compRefereeID = compRefereeID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.compRefereeID);
	}

	@Override
	public int hashCode() {
		return this.compRefereeID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		CompRefereeId other = (CompRefereeId) obj;
		return (this.compRefereeID == other.compRefereeID);
	}

	private void fromString(String str) {
		this.compRefereeID = Integer.parseInt(str);
	}
}