package de.regatta_hd.aquarius.db.model;

import java.util.Date;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "Comp")
@IdClass(CompId.class)
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class Comp {
	@Basic
	@Column(name = "Comp_Cancelled")
	private boolean cancelled;

	@Basic
	@Column(name = "Comp_DateTime", columnDefinition = "datetime")
	private Date dateTime;

	@Basic
	@Column(name = "Comp_Dummy")
	private boolean dummy;

	@OneToMany(targetEntity = CompEntries.class, mappedBy = "comp", cascade = CascadeType.MERGE)
	@OrderBy("lane")
	private Set<CompEntries> compEntries;

	@Basic
	@Column(name = "Comp_GroupValue")
	private short groupValue;

	@Basic
	@Column(name = "Comp_HeatNumber")
	@ToString.Include(rank = 10)
	private Short heatNumber;

	@Id
	@Column(name = "Comp_ID", columnDefinition = "int identity")
	private int id;

	@Basic
	@Column(name = "Comp_Label", length = 32)
	@ToString.Include(rank = 9)
	private String label;

	@Basic
	@Column(name = "Comp_Locked")
	private boolean locked;

	@Basic
	@Column(name = "Comp_Number")
	@ToString.Include(rank = 8)
	private short number;

	@OneToMany(targetEntity = CompReferee.class, mappedBy = "comp", cascade = CascadeType.MERGE)
	private Set<CompReferee> compReferees;

	@Basic
	@Column(name = "Comp_Round")
	@ToString.Include(rank = 7)
	private Short round;

	@Basic
	@Column(name = "Comp_RoundCode", length = 8)
	@ToString.Include(rank = 6)
	private String roundCode;

	@Basic
	@Column(name = "Comp_State")
	private byte state;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Comp_Event_ID_FK", nullable = false)
	private Event event;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Comp_Race_ID_FK")
	private Offer offer;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Comp_RMDetail_ID_FK")
	private RaceModeDetail raceModeDetail;

	@OneToMany(targetEntity = ReportInfo.class, mappedBy = "comp", cascade = CascadeType.MERGE)
	private Set<ReportInfo> reportInfos;
}