package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

import lombok.Data;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Crew
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
@Data
public class CrewId implements Serializable {

	private static final long serialVersionUID = 1390916925127203140L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Crew");
		} catch (ClassNotFoundException e) {
			throw new IllegalStateException(e);
		}
	}

	private int id;
}