package de.regatta_hd.aquarius.db.model;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "Crew")
@IdClass(de.regatta_hd.aquarius.db.model.CrewId.class)
public class Crew {
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Crew_Athlete_ID_FK", nullable = false)
	private Athlet athlet;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Crew_Club_ID_FK", nullable = false)
	private Club club;

	@Id
	@Column(name = "Crew_ID", columnDefinition = "int identity")
	private int crewID;

	@Basic
	@Column(name = "Crew_IsCox")
	private boolean crewIsCox;

	@Basic
	@Column(name = "Crew_Pos")
	private byte crewPos;

	@Basic
	@Column(name = "Crew_RoundFrom")
	private short crewRoundFrom;

	@Basic
	@Column(name = "Crew_RoundTo")
	private short crewRoundTo;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Crew_Entry_ID_FK", nullable = false)
	private Entry entry;

	public Crew() {
	}

	public Crew(int crewID) {
		this.crewID = crewID;
	}

	public Athlet getAthlet() {
		return this.athlet;
	}

	public void setAthlet(Athlet athlet) {
		this.athlet = athlet;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public int getCrewID() {
		return this.crewID;
	}

	public void setCrewID(int crewID) {
		this.crewID = crewID;
	}

	public boolean isCrewIsCox() {
		return this.crewIsCox;
	}

	public void setCrewIsCox(boolean crewIsCox) {
		this.crewIsCox = crewIsCox;
	}

	public byte getCrewPos() {
		return this.crewPos;
	}

	public void setCrewPos(byte crewPos) {
		this.crewPos = crewPos;
	}

	public short getCrewRoundFrom() {
		return this.crewRoundFrom;
	}

	public void setCrewRoundFrom(short crewRoundFrom) {
		this.crewRoundFrom = crewRoundFrom;
	}

	public short getCrewRoundTo() {
		return this.crewRoundTo;
	}

	public void setCrewRoundTo(short crewRoundTo) {
		this.crewRoundTo = crewRoundTo;
	}

	public Entry getEntry() {
		return this.entry;
	}

	public void setEntry(Entry entry) {
		this.entry = entry;
	}
}