package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Crew
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CrewId implements Serializable {

	private static final long serialVersionUID = 1390916925127203140L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Crew");
		} catch (Exception e) {
		}
	}

	public int crewID;

	public CrewId() {
	}

	public CrewId(String str) {
		fromString(str);
	}

	public int getCrewID() {
		return this.crewID;
	}

	public void setCrewID(int crewID) {
		this.crewID = crewID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.crewID);
	}

	@Override
	public int hashCode() {
		return this.crewID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		CrewId other = (CrewId) obj;
		return (this.crewID == other.crewID);
	}

	private void fromString(String str) {
		this.crewID = Integer.parseInt(str);
	}
}