package de.regatta_hd.aquarius.db.model;

import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "CupPointTable")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class CupPointTable {
	@Basic
	@Column(columnDefinition = "nvarchar", length = 32)
	private String caption;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Parent_ID")
	private CupPointTable cupPointTable;

	@OneToMany(targetEntity = CupPointTable.class, mappedBy = "cupPointTable", cascade = CascadeType.MERGE)
	private Set<CupPointTable> cupPointTables ;

	@OneToMany(targetEntity = Cup.class, mappedBy = "pointTable", cascade = CascadeType.MERGE)
	private Set<Cup> cups;

	@Id
	@Column(columnDefinition = "int identity")
	private int id;

	@Basic
	private Short lap;

	@Basic
	private Double points;

	@Basic
	private Byte rank;

	@Basic
	private Short round;
}