package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.CupPointTable
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CupPointTableId implements Serializable {

	private static final long serialVersionUID = -2912160504807058537L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.CupPointTable");
		} catch (Exception e) {
		}
	}

	public int id;

	public CupPointTableId() {
	}

	public CupPointTableId(String str) {
		fromString(str);
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return String.valueOf(this.id);
	}

	@Override
	public int hashCode() {
		return this.id;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		CupPointTableId other = (CupPointTableId) obj;
		return (this.id == other.id);
	}

	private void fromString(String str) {
		this.id = Integer.parseInt(str);
	}
}