package de.regatta_hd.aquarius.db.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "CupPointTable")
@IdClass(de.regatta_hd.aquarius.db.model.CupPointTableId.class)
public class CupPointTable {
	@Basic
	@Column(columnDefinition = "nvarchar", length = 32)
	private String caption;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Parent_ID")
	private CupPointTable cupPointTable;

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.CupPointTable.class, mappedBy = "cupPointTable", cascade = CascadeType.MERGE)
	private Set<CupPointTable> cupPointTables = new HashSet<>();

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.Cup.class, mappedBy = "cupPointTable", cascade = CascadeType.MERGE)
	private Set<Cup> cups = new HashSet<>();

	@Id
	@Column(columnDefinition = "int identity")
	private int id;

	@Basic
	private Short lap;

	@Basic
	private Double points;

	@Basic
	private Byte rank;

	@Basic
	private Short round;

	public CupPointTable() {
	}

	public CupPointTable(int id) {
		this.id = id;
	}

	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	public CupPointTable getCupPointTable() {
		return this.cupPointTable;
	}

	public void setCupPointTable(CupPointTable cupPointTable) {
		this.cupPointTable = cupPointTable;
	}

	public Set<CupPointTable> getCupPointTables() {
		return this.cupPointTables;
	}

	public void setCupPointTables(Set<CupPointTable> cupPointTables) {
		this.cupPointTables = cupPointTables;
	}

	public Set<Cup> getCups() {
		return this.cups;
	}

	public void setCups(Set<Cup> cups) {
		this.cups = cups;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Short getLap() {
		return this.lap;
	}

	public void setLap(Short lap) {
		this.lap = lap;
	}

	public Double getPoints() {
		return this.points;
	}

	public void setPoints(Double points) {
		this.points = points;
	}

	public Byte getRank() {
		return this.rank;
	}

	public void setRank(Byte rank) {
		this.rank = rank;
	}

	public Short getRound() {
		return this.round;
	}

	public void setRound(Short round) {
		this.round = round;
	}
}