package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Entry
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class EntryId implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -4414754143963767606L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Entry");
		} catch (Exception e) {
		}
	}

	public int entryID;

	public EntryId() {
	}

	public EntryId(String str) {
		fromString(str);
	}

	public int getEntryID() {
		return this.entryID;
	}

	public void setEntryID(int entryID) {
		this.entryID = entryID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.entryID);
	}

	@Override
	public int hashCode() {
		return this.entryID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		EntryId other = (EntryId) obj;
		return (this.entryID == other.entryID);
	}

	private void fromString(String str) {
		this.entryID = Integer.parseInt(str);
	}
}