package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Entry
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class EntryId implements Serializable {

	private static final long serialVersionUID = -4414754143963767606L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Entry");
		} catch (ClassNotFoundException e) {
		}
	}

	private int id;
}