package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.EntryLabel
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class EntryLabelId implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -5970601311571149673L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.EntryLabel");
		} catch (Exception e) {
		}
	}

	public int elId;

	public EntryLabelId() {
	}

	public EntryLabelId(String str) {
		fromString(str);
	}

	public int getElId() {
		return this.elId;
	}

	public void setElId(int elId) {
		this.elId = elId;
	}

	@Override
	public String toString() {
		return String.valueOf(this.elId);
	}

	@Override
	public int hashCode() {
		return this.elId;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		EntryLabelId other = (EntryLabelId) obj;
		return (this.elId == other.elId);
	}

	private void fromString(String str) {
		this.elId = Integer.parseInt(str);
	}
}