package de.regatta_hd.aquarius.db.model;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "EntryLabel")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class EntryLabel {
	@Basic
	@Column(name = "EL_IsClubMultiNOC")
	private boolean clubMultiNOC;

	@Basic
	@Column(name = "EL_IsCrewClubMultiNOC")
	private boolean crewClubMultiNOC;

	@Basic
	@Column(name = "EL_RoundFrom")
	@ToString.Include(rank = 9)
	private short roundFrom;

	@Basic
	@Column(name = "EL_RoundTo")
	@ToString.Include(rank = 8)
	private short roundTo;

	@Id
	@Column(name = "EL_ID", columnDefinition = "int identity")
	private int id;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "EL_Entry_ID_FK", nullable = false)
	private Registration registration;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "EL_Label_ID_FK", nullable = false)
	@ToString.Include(rank = 10)
	private Label label;
}