package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Event
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class EventId implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -6431551795701004624L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Event");
		} catch (Exception e) {
		}
	}

	public int eventID;

	public EventId() {
	}

	public EventId(String str) {
		fromString(str);
	}

	public int getEventID() {
		return this.eventID;
	}

	public void setEventID(int eventID) {
		this.eventID = eventID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.eventID);
	}

	@Override
	public int hashCode() {
		return this.eventID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		EventId other = (EventId) obj;
		return (this.eventID == other.eventID);
	}

	private void fromString(String str) {
		this.eventID = Integer.parseInt(str);
	}
}