package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Event
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class EventId implements Serializable {

	private static final long serialVersionUID = -6431551795701004624L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Event");
		} catch (ClassNotFoundException e) {
			throw new IllegalStateException(e);
		}
	}

	private int id;
}