package de.regatta_hd.aquarius.db.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "Label")
@IdClass(de.regatta_hd.aquarius.db.model.LabelId.class)
public class Label {
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Label_Club_ID_FK")
	private Club club;

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.EntryLabel.class, mappedBy = "label", cascade = CascadeType.MERGE)
	private Set<EntryLabel> entryLabels = new HashSet<>();

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.Entry.class, mappedBy = "label", cascade = CascadeType.MERGE)
	private Set<Entry> entrys = new HashSet<>();

	@Id
	@Column(name = "Label_ID", columnDefinition = "int identity")
	private int labelID;

	@Basic
	@Column(name = "Label_IsTeam")
	private Boolean labelIsTeam;

	@Basic
	@Column(name = "Label_Long", nullable = false, length = 512)
	private String labelLong;

	@Basic
	@Column(name = "Label_Short", nullable = false, length = 256)
	private String labelShort;

	public Label() {
	}

	public Label(int labelID) {
		this.labelID = labelID;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public Set<EntryLabel> getEntryLabels() {
		return this.entryLabels;
	}

	public void setEntryLabels(Set<EntryLabel> entryLabels) {
		this.entryLabels = entryLabels;
	}

	public Set<Entry> getEntrys() {
		return this.entrys;
	}

	public void setEntrys(Set<Entry> entrys) {
		this.entrys = entrys;
	}

	public int getLabelID() {
		return this.labelID;
	}

	public void setLabelID(int labelID) {
		this.labelID = labelID;
	}

	public Boolean isLabelIsTeam() {
		return this.labelIsTeam;
	}

	public void setLabelIsTeam(Boolean labelIsTeam) {
		this.labelIsTeam = labelIsTeam;
	}

	public String getLabelLong() {
		return this.labelLong;
	}

	public void setLabelLong(String labelLong) {
		this.labelLong = labelLong;
	}

	public String getLabelShort() {
		return this.labelShort;
	}

	public void setLabelShort(String labelShort) {
		this.labelShort = labelShort;
	}
}