package de.regatta_hd.aquarius.db.model;

import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "Label")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class Label {
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Label_Club_ID_FK")
	private Club club;

	@OneToMany(targetEntity = EntryLabel.class, mappedBy = "label", cascade = CascadeType.MERGE)
	private Set<EntryLabel> labels;

	@OneToMany(targetEntity = Entry.class, mappedBy = "label", cascade = CascadeType.MERGE)
	private Set<Entry> entries;

	@Id
	@Column(name = "Label_ID", columnDefinition = "int identity")
	private int id;

	@Basic
	@Column(name = "Label_IsTeam")
	private Boolean isTeam;

	@Basic
	@Column(name = "Label_Long", nullable = false, length = 512)
	@ToString.Include
	private String labelLong;

	@Basic
	@Column(name = "Label_Short", nullable = false, length = 256)
	@ToString.Include
	private String labelShort;
}