package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

import lombok.Data;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Label
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
@Data
public class LabelId implements Serializable {

	private static final long serialVersionUID = -8007962253549117860L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Label");
		} catch (ClassNotFoundException e) {
			throw new IllegalStateException(e);
		}
	}

	private int id;
}