package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Label
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class LabelId implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -8007962253549117860L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Label");
		} catch (Exception e) {
		}
	}

	public int labelID;

	public LabelId() {
	}

	public LabelId(String str) {
		fromString(str);
	}

	public int getLabelID() {
		return this.labelID;
	}

	public void setLabelID(int labelID) {
		this.labelID = labelID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.labelID);
	}

	@Override
	public int hashCode() {
		return this.labelID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		LabelId other = (LabelId) obj;
		return (this.labelID == other.labelID);
	}

	private void fromString(String str) {
		this.labelID = Integer.parseInt(str);
	}
}