package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.MetaData
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class MetaDataId implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = 3330169054806794644L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.MetaData");
		} catch (Exception e) {
		}
	}

	public String metaDataKey;

	public MetaDataId() {
	}

	public MetaDataId(String str) {
		fromString(str);
	}

	public String getMetaDataKey() {
		return this.metaDataKey;
	}

	public void setMetaDataKey(String metaDataKey) {
		this.metaDataKey = metaDataKey;
	}

	@Override
	public String toString() {
		return this.metaDataKey;
	}

	@Override
	public int hashCode() {
		return ((this.metaDataKey == null) ? 0 : this.metaDataKey.hashCode());
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		MetaDataId other = (MetaDataId) obj;
		return ((this.metaDataKey == null && other.metaDataKey == null)
				|| (this.metaDataKey != null && this.metaDataKey.equals(other.metaDataKey)));
	}

	private void fromString(String str) {
		if ("null".equals(str))
			this.metaDataKey = null;
		else
			this.metaDataKey = str;
	}
}