package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Nation
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class NationId implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -530655267994798977L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Nation");
		} catch (Exception e) {
		}
	}

	public int nationID;

	public NationId() {
	}

	public NationId(String str) {
		fromString(str);
	}

	public int getNationID() {
		return this.nationID;
	}

	public void setNationID(int nationID) {
		this.nationID = nationID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.nationID);
	}

	@Override
	public int hashCode() {
		return this.nationID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		NationId other = (NationId) obj;
		return (this.nationID == other.nationID);
	}

	private void fromString(String str) {
		this.nationID = Integer.parseInt(str);
	}
}