package de.regatta_hd.aquarius.db.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "Offer")
@IdClass(OfferId.class)
// lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class Offer {
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Offer_AgeClass_ID_FK", nullable = false)
	private AgeClass ageClass;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Offer_BoatClass_ID_FK", nullable = false)
	private BoatClass boatClass;

	@OneToMany(targetEntity = Comp.class, mappedBy = "offer", cascade = CascadeType.MERGE)
	private Set<Comp> comps = new HashSet<>();

	@OneToMany(targetEntity = Cup.class, mappedBy = "offer", cascade = CascadeType.MERGE)
	private Set<Cup> cups = new HashSet<>();

	@OneToMany(targetEntity = Entry.class, mappedBy = "offer", cascade = CascadeType.MERGE)
	private Set<Entry> entrys = new HashSet<>();

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Offer_Event_ID_FK", nullable = false)
	private Event event;

	@Basic
	@Column(name = "Offer_BibSeed")
	private Short bibSeed;

	@Basic
	@Column(name = "Offer_Cancelled")
	private Boolean cancelled;

	@Basic
	@Column(name = "Offer_Comment", length = 32)
	private String comment;

	@Basic
	@Column(name = "Offer_Distance")
	private short distance;

	@Basic
	@Column(name = "Offer_Driven")
	private Boolean driven;

	@Basic
	@Column(name = "Offer_EventDay")
	private Integer eventDay;

	@Basic
	@Column(name = "Offer_Fee", columnDefinition = "smallmoney")
	private double fee;

	@Basic
	@Column(name = "Offer_ForceDriven")
	private boolean forceDriven;

	@Basic
	@Column(name = "Offer_GroupMode")
	private byte groupMode;

	@Id
	@Column(name = "Offer_ID", columnDefinition = "int identity")
	@ToString.Include(rank = 10)
	private int id;

	@Basic
	@Column(name = "Offer_IsLightweight")
	private boolean isLightweight;

	@Basic
	@Column(name = "Offer_LongLabel", length = 64)
	@ToString.Include
	private String longLabel;

	@Basic
	@Column(name = "Offer_Prize", length = 128)
	private String prize;

	@Basic
	@Column(name = "Offer_RaceNumber", nullable = false, length = 8)
	@ToString.Include(rank = 9)
	private String raceNumber;

	@Basic
	@Column(name = "Offer_RaceType")
	private byte raceType;

	@Basic
	@Column(name = "Offer_ShortLabel", length = 32)
	private String shortLabel;

	@Basic
	@Column(name = "Offer_SortValue")
	private int sortValue;

	@Basic
	@Column(name = "Offer_Splits")
	private Integer splits;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Offer_RaceMode_ID_FK")
	private RaceMode raceMode;

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.ReportInfo.class, mappedBy = "offer", cascade = CascadeType.MERGE)
	private Set<ReportInfo> reportInfos = new HashSet<>();

	public Offer() {
	}

	public AgeClass getAgeClass() {
		return this.ageClass;
	}

	public void setAgeClass(AgeClass ageClass) {
		this.ageClass = ageClass;
	}

	public BoatClass getBoatClass() {
		return this.boatClass;
	}

	public void setBoatClass(BoatClass boatClass) {
		this.boatClass = boatClass;
	}

	public Set<Comp> getComps() {
		return this.comps;
	}

	public void setComps(Set<Comp> comps) {
		this.comps = comps;
	}

	public Set<Cup> getCups() {
		return this.cups;
	}

	public void setCups(Set<Cup> cups) {
		this.cups = cups;
	}

	public Set<Entry> getEntrys() {
		return this.entrys;
	}

	public void setEntrys(Set<Entry> entrys) {
		this.entrys = entrys;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public RaceMode getRaceMode() {
		return this.raceMode;
	}

	public void setRaceMode(RaceMode raceMode) {
		this.raceMode = raceMode;
	}

	public Set<ReportInfo> getReportInfos() {
		return this.reportInfos;
	}

	public void setReportInfos(Set<ReportInfo> reportInfos) {
		this.reportInfos = reportInfos;
	}
}