package de.regatta_hd.aquarius.db.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "Offer")
@IdClass(de.regatta_hd.aquarius.db.model.OfferId.class)
public class Offer {
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Offer_AgeClass_ID_FK", nullable = false)
	private AgeClass ageClass;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Offer_BoatClass_ID_FK", nullable = false)
	private BoatClass boatClass;

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.Comp.class, mappedBy = "offer", cascade = CascadeType.MERGE)
	private Set<Comp> comps = new HashSet<>();

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.Cup.class, mappedBy = "offer", cascade = CascadeType.MERGE)
	private Set<Cup> cups = new HashSet<>();

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.Entry.class, mappedBy = "offer", cascade = CascadeType.MERGE)
	private Set<Entry> entrys = new HashSet<>();

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Offer_Event_ID_FK", nullable = false)
	private Event event;

	@Basic
	@Column(name = "Offer_BibSeed")
	private Short offerBibSeed;

	@Basic
	@Column(name = "Offer_Cancelled")
	private Boolean offerCancelled;

	@Basic
	@Column(name = "Offer_Comment", length = 32)
	private String offerComment;

	@Basic
	@Column(name = "Offer_Distance")
	private short offerDistance;

	@Basic
	@Column(name = "Offer_Driven")
	private Boolean offerDriven;

	@Basic
	@Column(name = "Offer_EventDay")
	private Integer offerEventDay;

	@Basic
	@Column(name = "Offer_Fee", columnDefinition = "smallmoney")
	private double offerFee;

	@Basic
	@Column(name = "Offer_ForceDriven")
	private boolean offerForceDriven;

	@Basic
	@Column(name = "Offer_GroupMode")
	private byte offerGroupMode;

	@Id
	@Column(name = "Offer_ID", columnDefinition = "int identity")
	private int offerID;

	@Basic
	@Column(name = "Offer_IsLightweight")
	private boolean offerIsLightweight;

	@Basic
	@Column(name = "Offer_LongLabel", length = 64)
	private String offerLongLabel;

	@Basic
	@Column(name = "Offer_Prize", length = 128)
	private String offerPrize;

	@Basic
	@Column(name = "Offer_RaceNumber", nullable = false, length = 8)
	private String offerRaceNumber;

	@Basic
	@Column(name = "Offer_RaceType")
	private byte offerRaceType;

	@Basic
	@Column(name = "Offer_ShortLabel", length = 32)
	private String offerShortLabel;

	@Basic
	@Column(name = "Offer_SortValue")
	private int offerSortValue;

	@Basic
	@Column(name = "Offer_Splits")
	private Integer offerSplits;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Offer_RaceMode_ID_FK")
	private RaceMode raceMode;

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.ReportInfo.class, mappedBy = "offer", cascade = CascadeType.MERGE)
	private Set<ReportInfo> reportInfos = new HashSet<>();

	public Offer() {
	}

	public Offer(int offerID) {
		this.offerID = offerID;
	}

	public AgeClass getAgeClass() {
		return this.ageClass;
	}

	public void setAgeClass(AgeClass ageClass) {
		this.ageClass = ageClass;
	}

	public BoatClass getBoatClass() {
		return this.boatClass;
	}

	public void setBoatClass(BoatClass boatClass) {
		this.boatClass = boatClass;
	}

	public Set<Comp> getComps() {
		return this.comps;
	}

	public void setComps(Set<Comp> comps) {
		this.comps = comps;
	}

	public Set<Cup> getCups() {
		return this.cups;
	}

	public void setCups(Set<Cup> cups) {
		this.cups = cups;
	}

	public Set<Entry> getEntrys() {
		return this.entrys;
	}

	public void setEntrys(Set<Entry> entrys) {
		this.entrys = entrys;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Short getOfferBibSeed() {
		return this.offerBibSeed;
	}

	public void setOfferBibSeed(Short offerBibSeed) {
		this.offerBibSeed = offerBibSeed;
	}

	public Boolean isOfferCancelled() {
		return this.offerCancelled;
	}

	public void setOfferCancelled(Boolean offerCancelled) {
		this.offerCancelled = offerCancelled;
	}

	public String getOfferComment() {
		return this.offerComment;
	}

	public void setOfferComment(String offerComment) {
		this.offerComment = offerComment;
	}

	public short getOfferDistance() {
		return this.offerDistance;
	}

	public void setOfferDistance(short offerDistance) {
		this.offerDistance = offerDistance;
	}

	public Boolean isOfferDriven() {
		return this.offerDriven;
	}

	public void setOfferDriven(Boolean offerDriven) {
		this.offerDriven = offerDriven;
	}

	public Integer getOfferEventDay() {
		return this.offerEventDay;
	}

	public void setOfferEventDay(Integer offerEventDay) {
		this.offerEventDay = offerEventDay;
	}

	public double getOfferFee() {
		return this.offerFee;
	}

	public void setOfferFee(double offerFee) {
		this.offerFee = offerFee;
	}

	public boolean isOfferForceDriven() {
		return this.offerForceDriven;
	}

	public void setOfferForceDriven(boolean offerForceDriven) {
		this.offerForceDriven = offerForceDriven;
	}

	public byte getOfferGroupMode() {
		return this.offerGroupMode;
	}

	public void setOfferGroupMode(byte offerGroupMode) {
		this.offerGroupMode = offerGroupMode;
	}

	public int getOfferID() {
		return this.offerID;
	}

	public void setOfferID(int offerID) {
		this.offerID = offerID;
	}

	public boolean isOfferIsLightweight() {
		return this.offerIsLightweight;
	}

	public void setOfferIsLightweight(boolean offerIsLightweight) {
		this.offerIsLightweight = offerIsLightweight;
	}

	public String getOfferLongLabel() {
		return this.offerLongLabel;
	}

	public void setOfferLongLabel(String offerLongLabel) {
		this.offerLongLabel = offerLongLabel;
	}

	public String getOfferPrize() {
		return this.offerPrize;
	}

	public void setOfferPrize(String offerPrize) {
		this.offerPrize = offerPrize;
	}

	public String getOfferRaceNumber() {
		return this.offerRaceNumber;
	}

	public void setOfferRaceNumber(String offerRaceNumber) {
		this.offerRaceNumber = offerRaceNumber;
	}

	public byte getOfferRaceType() {
		return this.offerRaceType;
	}

	public void setOfferRaceType(byte offerRaceType) {
		this.offerRaceType = offerRaceType;
	}

	public String getOfferShortLabel() {
		return this.offerShortLabel;
	}

	public void setOfferShortLabel(String offerShortLabel) {
		this.offerShortLabel = offerShortLabel;
	}

	public int getOfferSortValue() {
		return this.offerSortValue;
	}

	public void setOfferSortValue(int offerSortValue) {
		this.offerSortValue = offerSortValue;
	}

	public Integer getOfferSplits() {
		return this.offerSplits;
	}

	public void setOfferSplits(Integer offerSplits) {
		this.offerSplits = offerSplits;
	}

	public RaceMode getRaceMode() {
		return this.raceMode;
	}

	public void setRaceMode(RaceMode raceMode) {
		this.raceMode = raceMode;
	}

	public Set<ReportInfo> getReportInfos() {
		return this.reportInfos;
	}

	public void setReportInfos(Set<ReportInfo> reportInfos) {
		this.reportInfos = reportInfos;
	}
}