package de.regatta_hd.aquarius.db.model;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "ProgressionRule")
@IdClass(de.regatta_hd.aquarius.db.model.ProgressionRuleId.class)
public class ProgressionRule {
	@Basic
	@Column(name = "PR_Arg")
	private Byte pRArg;

	@Basic
	@Column(name = "PR_Option")
	private Byte pROption;

	@Basic
	@Column(name = "PR_Order")
	private short pROrder;

	@Basic
	@Column(name = "PR_Type", nullable = false, length = 1)
	private String pRType;

	@Id
	@Column(name = "PR_ID", columnDefinition = "int identity")
	private int prId;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "PR_RMLap_ID_FK", nullable = false)
	private RaceModeDetail raceModeDetail;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "PR_Src_Lap_ID_FK")
	private RaceModeDetail raceModeDetail2;

	public ProgressionRule() {
	}

	public ProgressionRule(int prId) {
		this.prId = prId;
	}

	public Byte getpRArg() {
		return this.pRArg;
	}

	public void setpRArg(Byte pRArg) {
		this.pRArg = pRArg;
	}

	public Byte getpROption() {
		return this.pROption;
	}

	public void setpROption(Byte pROption) {
		this.pROption = pROption;
	}

	public short getpROrder() {
		return this.pROrder;
	}

	public void setpROrder(short pROrder) {
		this.pROrder = pROrder;
	}

	public String getpRType() {
		return this.pRType;
	}

	public void setpRType(String pRType) {
		this.pRType = pRType;
	}

	public int getPrId() {
		return this.prId;
	}

	public void setPrId(int prId) {
		this.prId = prId;
	}

	public RaceModeDetail getRaceModeDetail() {
		return this.raceModeDetail;
	}

	public void setRaceModeDetail(RaceModeDetail raceModeDetail) {
		this.raceModeDetail = raceModeDetail;
	}

	public RaceModeDetail getRaceModeDetail2() {
		return this.raceModeDetail2;
	}

	public void setRaceModeDetail2(RaceModeDetail raceModeDetail2) {
		this.raceModeDetail2 = raceModeDetail2;
	}
}