package de.regatta_hd.aquarius.db.model;

import jakarta.persistence.Basic;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "RaceMode_Detail")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class RaceModeDetail {
	@OneToMany(targetEntity = Heat.class, mappedBy = "raceModeDetail", cascade = CascadeType.MERGE)
	private Set<Heat> comps;

	@OneToMany(targetEntity = ProgressionRule.class, mappedBy = "raceModeDetail", cascade = CascadeType.MERGE)
	private Set<ProgressionRule> progressionRules;

	@OneToMany(targetEntity = ProgressionRule.class, mappedBy = "raceModeDetail2", cascade = CascadeType.MERGE)
	private Set<ProgressionRule> progressionRules2;

	@Basic
	@Column(name = "RMLap_Code", nullable = false, length = 8)
	@ToString.Include(rank = 6)
	private String code;

	@Id
	@Column(name = "RMLap_ID", columnDefinition = "int identity")
	private int id;

	@Basic
	@Column(name = "RMLap_Label", nullable = false, length = 8)
	@ToString.Include(rank = 10)
	private String label;

	@Basic
	@Column(name = "RMLap_Number")
	@ToString.Include(rank = 9)
	private Short number;

	@Basic
	@Column(name = "RMLap_QRText", length = 64)
	@ToString.Include(rank = 8)
	private String qrText;

	@Basic
	@Column(name = "RMLap_Round")
	@ToString.Include(rank = 7)
	private int round;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "RMLap_Range_ID_FK", nullable = false)
	private RaceModeRange range;
}