package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.RaceModeRange
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class RaceModeRangeId implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -5776640359151236256L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.RaceModeRange");
		} catch (Exception e) {
		}
	}

	public int rMRangeID;

	public RaceModeRangeId() {
	}

	public RaceModeRangeId(String str) {
		fromString(str);
	}

	public int getRMRangeID() {
		return this.rMRangeID;
	}

	public void setRMRangeID(int rMRangeID) {
		this.rMRangeID = rMRangeID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.rMRangeID);
	}

	@Override
	public int hashCode() {
		return this.rMRangeID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		RaceModeRangeId other = (RaceModeRangeId) obj;
		return (this.rMRangeID == other.rMRangeID);
	}

	private void fromString(String str) {
		this.rMRangeID = Integer.parseInt(str);
	}
}