package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.RaceModeDetail
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class RaceModeDetailId implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = 8002856776939940281L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.RaceModeDetail");
		} catch (Exception e) {
		}
	}

	public int rMLapID;

	public RaceModeDetailId() {
	}

	public RaceModeDetailId(String str) {
		fromString(str);
	}

	public int getRMLapID() {
		return this.rMLapID;
	}

	public void setRMLapID(int rMLapID) {
		this.rMLapID = rMLapID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.rMLapID);
	}

	@Override
	public int hashCode() {
		return this.rMLapID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		RaceModeDetailId other = (RaceModeDetailId) obj;
		return (this.rMLapID == other.rMLapID);
	}

	private void fromString(String str) {
		this.rMLapID = Integer.parseInt(str);
	}
}