package de.regatta_hd.aquarius.db.model;

import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "RaceMode_Range")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class RaceModeRange {
	@Basic
	@Column(name = "RMRange_From")
	@ToString.Include(rank = 10)
	private int from;

	@Id
	@Column(name = "RMRange_ID", columnDefinition = "int identity")
	private int id;

	@Basic
	@Column(name = "RMRange_To")
	@ToString.Include(rank = 9)
	private int to;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "RMRange_RM_ID_FK", nullable = false)
	@ToString.Include(rank = 8)
	private RaceMode raceMode;

	@OneToMany(targetEntity = RaceModeDetail.class, mappedBy = "range", cascade = CascadeType.MERGE)
	private Set<RaceModeDetail> raceModeDetails;
}