package de.regatta_hd.aquarius.db.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "RaceMode_Range")
@IdClass(de.regatta_hd.aquarius.db.model.RaceModeRangeId.class)
public class RaceModeRange {
	@Basic
	@Column(name = "RMRange_From")
	private int rMRangeFrom;

	@Id
	@Column(name = "RMRange_ID", columnDefinition = "int identity")
	private int rMRangeID;

	@Basic
	@Column(name = "RMRange_To")
	private int rMRangeTo;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "RMRange_RM_ID_FK", nullable = false)
	private RaceMode raceMode;

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.RaceModeDetail.class, mappedBy = "raceModeRange", cascade = CascadeType.MERGE)
	private Set<RaceModeDetail> raceModeDetails = new HashSet<>();

	public RaceModeRange() {
	}

	public RaceModeRange(int rMRangeID) {
		this.rMRangeID = rMRangeID;
	}

	public int getrMRangeFrom() {
		return this.rMRangeFrom;
	}

	public void setrMRangeFrom(int rMRangeFrom) {
		this.rMRangeFrom = rMRangeFrom;
	}

	public int getrMRangeID() {
		return this.rMRangeID;
	}

	public void setrMRangeID(int rMRangeID) {
		this.rMRangeID = rMRangeID;
	}

	public int getrMRangeTo() {
		return this.rMRangeTo;
	}

	public void setrMRangeTo(int rMRangeTo) {
		this.rMRangeTo = rMRangeTo;
	}

	public RaceMode getRaceMode() {
		return this.raceMode;
	}

	public void setRaceMode(RaceMode raceMode) {
		this.raceMode = raceMode;
	}

	public Set<RaceModeDetail> getRaceModeDetails() {
		return this.raceModeDetails;
	}

	public void setRaceModeDetails(Set<RaceModeDetail> raceModeDetails) {
		this.raceModeDetails = raceModeDetails;
	}
}