package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.RaceMode
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class RaceModeId implements Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -6741198599435821330L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.RaceMode");
		} catch (Exception e) {
		}
	}

	public int raceModeID;

	public RaceModeId() {
	}

	public RaceModeId(String str) {
		fromString(str);
	}

	public int getRaceModeID() {
		return this.raceModeID;
	}

	public void setRaceModeID(int raceModeID) {
		this.raceModeID = raceModeID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.raceModeID);
	}

	@Override
	public int hashCode() {
		return this.raceModeID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		RaceModeId other = (RaceModeId) obj;
		return (this.raceModeID == other.raceModeID);
	}

	private void fromString(String str) {
		this.raceModeID = Integer.parseInt(str);
	}
}