package de.regatta_hd.aquarius.db.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "RaceMode")
@IdClass(de.regatta_hd.aquarius.db.model.RaceModeId.class)
public class RaceMode {
	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.Event.class, mappedBy = "raceMode", cascade = CascadeType.MERGE)
	private Set<Event> events = new HashSet<>();

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.Offer.class, mappedBy = "raceMode", cascade = CascadeType.MERGE)
	private Set<Offer> offers = new HashSet<>();

	@Id
	@Column(name = "RaceMode_ID", columnDefinition = "int identity")
	private int raceModeID;

	@Basic
	@Column(name = "RaceMode_IsSystemMode")
	private boolean raceModeIsSystemMode;

	@Basic
	@Column(name = "RaceMode_LaneCount")
	private short raceModeLaneCount;

	@OneToMany(targetEntity = de.regatta_hd.aquarius.db.model.RaceModeRange.class, mappedBy = "raceMode", cascade = CascadeType.MERGE)
	private Set<RaceModeRange> raceModeRanges = new HashSet<>();

	@Basic
	@Column(name = "RaceMode_Title", nullable = false, length = 32)
	private String raceModeTitle;

	public RaceMode() {
	}

	public RaceMode(int raceModeID) {
		this.raceModeID = raceModeID;
	}

	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	public Set<Offer> getOffers() {
		return this.offers;
	}

	public void setOffers(Set<Offer> offers) {
		this.offers = offers;
	}

	public int getRaceModeID() {
		return this.raceModeID;
	}

	public void setRaceModeID(int raceModeID) {
		this.raceModeID = raceModeID;
	}

	public boolean isRaceModeIsSystemMode() {
		return this.raceModeIsSystemMode;
	}

	public void setRaceModeIsSystemMode(boolean raceModeIsSystemMode) {
		this.raceModeIsSystemMode = raceModeIsSystemMode;
	}

	public short getRaceModeLaneCount() {
		return this.raceModeLaneCount;
	}

	public void setRaceModeLaneCount(short raceModeLaneCount) {
		this.raceModeLaneCount = raceModeLaneCount;
	}

	public Set<RaceModeRange> getRaceModeRanges() {
		return this.raceModeRanges;
	}

	public void setRaceModeRanges(Set<RaceModeRange> raceModeRanges) {
		this.raceModeRanges = raceModeRanges;
	}

	public String getRaceModeTitle() {
		return this.raceModeTitle;
	}

	public void setRaceModeTitle(String raceModeTitle) {
		this.raceModeTitle = raceModeTitle;
	}
}