package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Referee
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
public class RefereeId implements Serializable {

	private static final long serialVersionUID = -1934624990528901142L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Referee");
		} catch (Exception e) {
		}
	}

	public int refereeID;

	public RefereeId() {
	}

	public RefereeId(String str) {
		fromString(str);
	}

	public int getRefereeID() {
		return this.refereeID;
	}

	public void setRefereeID(int refereeID) {
		this.refereeID = refereeID;
	}

	@Override
	public String toString() {
		return String.valueOf(this.refereeID);
	}

	@Override
	public int hashCode() {
		return this.refereeID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || obj.getClass() != getClass())
			return false;

		RefereeId other = (RefereeId) obj;
		return (this.refereeID == other.refereeID);
	}

	private void fromString(String str) {
		this.refereeID = Integer.parseInt(str);
	}
}