package de.regatta_hd.aquarius.db.model;

import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "Referee")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class Referee {
	@OneToMany(targetEntity = CompReferee.class, mappedBy = "referee", cascade = CascadeType.MERGE)
	private Set<CompReferee> compReferees;

	@OneToMany(targetEntity = Regatta.class, mappedBy = "referee", cascade = CascadeType.MERGE)
	private Set<Regatta> regattas;

	@ManyToMany(targetEntity = Regatta.class, mappedBy = "referees", cascade = CascadeType.MERGE)
	private Set<Regatta> regattas2;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Referee_Nation_ID_FK")
	private Nation nation;

	@Basic
	@Column(name = "Referee_City", length = 32)
	private String city;

	@Basic
	@Column(name = "Referee_ExternID")
	private Integer externID;

	@Basic
	@Column(name = "Referee_FirstName", nullable = false, length = 32)
	private String firstName;

	@Id
	@Column(name = "Referee_ID", columnDefinition = "int identity")
	private int id;

	@Basic
	@Column(name = "Referee_LastName", nullable = false, length = 64)
	private String lastName;

	@Basic
	@Column(name = "Referee_LicenceState")
	private byte licenceState;
}