package de.regatta_hd.aquarius.db.model;

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "ReportInfo")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class ReportInfo {
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Report_Comp_ID_FK")
	private Comp comp;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Report_Event_ID_FK")
	private Event event;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Report_Race_ID_FK")
	private Offer offer;

	@Basic
	@Column(name = "Report_Backend", nullable = false, length = 4)
	private String backend;

	@Basic
	@Column(name = "Report_Code", nullable = false, length = 16)
	private String code;

	@Basic
	@Column(name = "Report_Date", columnDefinition = "datetime")
	private Date date;

	@Basic
	@Column(name = "Report_Generated", columnDefinition = "datetime")
	@ToString.Include(rank = 10)
	private Date generated;

	@Id
	@Column(name = "ReportInfo_ID", columnDefinition = "int identity")
	private int id;

	@Basic
	@Column(name = "Report_Round")
	private Byte round;

	@Basic
	@Column(name = "Report_VersionMajor")
	@ToString.Include(rank = 5)
	private Byte versionMajor;

	@Basic
	@Column(name = "Report_VersionMinor")
	@ToString.Include(rank = 4)
	private Byte versionMinor;
}