package de.regatta_hd.aquarius.db.model;

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "ReportInfo")
@IdClass(de.regatta_hd.aquarius.db.model.ReportInfoId.class)
public class ReportInfo {
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Report_Comp_ID_FK")
	private Comp comp;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Report_Event_ID_FK")
	private Event event;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Report_Race_ID_FK")
	private Offer offer;

	@Basic
	@Column(name = "Report_Backend", nullable = false, length = 4)
	private String reportBackend;

	@Basic
	@Column(name = "Report_Code", nullable = false, length = 16)
	private String reportCode;

	@Basic
	@Column(name = "Report_Date", columnDefinition = "datetime")
	private Date reportDate;

	@Basic
	@Column(name = "Report_Generated", columnDefinition = "datetime")
	private Date reportGenerated;

	@Id
	@Column(name = "ReportInfo_ID", columnDefinition = "int identity")
	private int reportInfoID;

	@Basic
	@Column(name = "Report_Round")
	private Byte reportRound;

	@Basic
	@Column(name = "Report_VersionMajor")
	private Byte reportVersionMajor;

	@Basic
	@Column(name = "Report_VersionMinor")
	private Byte reportVersionMinor;

	public ReportInfo() {
	}

	public ReportInfo(int reportInfoID) {
		this.reportInfoID = reportInfoID;
	}

	public Comp getComp() {
		return this.comp;
	}

	public void setComp(Comp comp) {
		this.comp = comp;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Offer getOffer() {
		return this.offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	public String getReportBackend() {
		return this.reportBackend;
	}

	public void setReportBackend(String reportBackend) {
		this.reportBackend = reportBackend;
	}

	public String getReportCode() {
		return this.reportCode;
	}

	public void setReportCode(String reportCode) {
		this.reportCode = reportCode;
	}

	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	public Date getReportGenerated() {
		return this.reportGenerated;
	}

	public void setReportGenerated(Date reportGenerated) {
		this.reportGenerated = reportGenerated;
	}

	public int getReportInfoID() {
		return this.reportInfoID;
	}

	public void setReportInfoID(int reportInfoID) {
		this.reportInfoID = reportInfoID;
	}

	public Byte getReportRound() {
		return this.reportRound;
	}

	public void setReportRound(Byte reportRound) {
		this.reportRound = reportRound;
	}

	public Byte getReportVersionMajor() {
		return this.reportVersionMajor;
	}

	public void setReportVersionMajor(Byte reportVersionMajor) {
		this.reportVersionMajor = reportVersionMajor;
	}

	public Byte getReportVersionMinor() {
		return this.reportVersionMinor;
	}

	public void setReportVersionMinor(Byte reportVersionMinor) {
		this.reportVersionMinor = reportVersionMinor;
	}
}