package de.regatta_hd.aquarius.db.model;

import java.io.Serializable;
import lombok.Data;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.model.Result
 *
 * Auto-generated by: org.apache.openjpa.enhance.ApplicationIdTool
 */
@Data
public class ResultId implements Serializable {

	private static final long serialVersionUID = 1140277898086880875L;

	static {
		// register persistent class in JVM
		try {
			Class.forName("de.regatta_hd.aquarius.db.model.Result");
		} catch (ClassNotFoundException e) {
			throw new IllegalStateException(e);
		}
	}

	private int heatRegistrationId;

	private byte splitNr;
}