package de.regatta_hd.aquarius.db.model;

import jakarta.persistence.Basic;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.Table;
import java.util.List;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "BoatClass")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class BoatClass {
	@Basic
	@Column(name = "BoatClass_Abbr", nullable = false, length = 8)
	@ToString.Include(rank = 10)
	private String abbreviation;

	@Basic
	@Column(name = "BoatClass_Caption", nullable = false, length = 50)
	@ToString.Include(rank = 9)
	private String caption;

	@Basic
	@Column(name = "BoatClass_Coxed")
	private byte coxed;

	@Id
	@Column(name = "BoatClass_ID", columnDefinition = "int identity")
	@ToString.Include(rank = 1)
	private int id;

	@Basic
	@Column(name = "BoatClass_NumRowers")
	private byte numRowers;

	@OneToMany(targetEntity = Offer.class, mappedBy = "boatClass", cascade = CascadeType.MERGE)
	@OrderBy("raceNumber")
	private List<Offer> offers;
}