package de.regatta_hd.aquarius.db.model;

import jakarta.persistence.Basic;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "RaceMode")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class RaceMode {
	@OneToMany(targetEntity = Regatta.class, mappedBy = "raceMode", cascade = CascadeType.MERGE)
	private Set<Regatta> events;

	@OneToMany(targetEntity = Offer.class, mappedBy = "raceMode", cascade = CascadeType.MERGE)
	private Set<Offer> offers;

	@Id
	@Column(name = "RaceMode_ID", columnDefinition = "int identity")
	private int id;

	@Basic
	@Column(name = "RaceMode_IsSystemMode")
	@ToString.Include(rank = 8)
	private boolean isSystemMode;

	@Basic
	@Column(name = "RaceMode_LaneCount")
	@ToString.Include(rank = 9)
	private short laneCount;

	@OneToMany(targetEntity = RaceModeRange.class, mappedBy = "raceMode", cascade = CascadeType.MERGE)
	private Set<RaceModeRange> ranges;

	@Basic
	@Column(name = "RaceMode_Title", nullable = false, length = 32)
	@ToString.Include(rank = 10)
	private String title;
}