package de.regatta_hd.aquarius.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "Crew")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class Crew {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Crew_ID")
	private int id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Crew_Athlete_ID_FK", nullable = false)
	@ToString.Include(rank = 8)
	private Athlet athlet;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Crew_Club_ID_FK", nullable = false)
	private Club club;

	@Column(name = "Crew_IsCox")
	private boolean isCox;

	@Column(name = "Crew_Pos")
	@ToString.Include(rank = 10)
	private byte pos;

	@Column(name = "Crew_RoundFrom")
	private short roundFrom;

	@Column(name = "Crew_RoundTo")
	private short roundTo;

	/**
	 * Contains the {@link Registration registration} this crew member belongs to.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Crew_Entry_ID_FK", nullable = false)
	private Registration registration;

	public String getName() {
		return this.athlet.getLastName() + ", " + this.athlet.getFirstName();
	}
}