package de.regatta_hd.aquarius.model;

import java.util.List;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "RaceMode_Detail")
//lombok
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class RaceModeDetail {

	@Id
	@Column(name = "RMLap_ID")
	private int id;

	@OneToMany(targetEntity = Heat.class, mappedBy = "raceModeDetail")
	private List<Heat> heats;

	@OneToMany(targetEntity = ProgressionRule.class, mappedBy = "raceModeDetail")
	private Set<ProgressionRule> progressionRules;

	@OneToMany(targetEntity = ProgressionRule.class, mappedBy = "raceModeDetail2")
	private Set<ProgressionRule> progressionRules2;

	@Column(name = "RMLap_Code", nullable = false, length = 8)
	@ToString.Include(rank = 6)
	private String code;

	@Column(name = "RMLap_Label", nullable = false, length = 8)
	@ToString.Include(rank = 10)
	private String label;

	@Column(name = "RMLap_Number")
	@ToString.Include(rank = 9)
	private Short number;

	@Column(name = "RMLap_QRText")
	@ToString.Include(rank = 8)
	private String qrText;

	@Column(name = "RMLap_Round")
	@ToString.Include(rank = 7)
	private int round;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RMLap_Range_ID_FK", nullable = false)
	private RaceModeRange range;
}