package de.regatta_hd.aquarius.model;

import java.time.Instant;
import java.util.List;
import java.util.Set;

import jakarta.persistence.Basic;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.ToString;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "dbo", name = "Event")
// lombok
@Data
@ToString(onlyExplicitlyIncluded = true)
public class Regatta {
	@Id
	@Column(name = "Event_ID", columnDefinition = "int identity")
	@ToString.Include(rank = 20)
	private int id;

	@Column(name = "Event_Title", nullable = false, length = 64)
	@ToString.Include(rank = 18)
	private String title;

	@Column(name = "Event_StartDate", nullable = false)
	private Instant startDate;

	@Column(name = "Event_EndDate", nullable = false)
	private Instant endDate;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Event_Club_ID_FK")
	private Club club;

	@OneToMany(targetEntity = Heat.class, mappedBy = "regatta", cascade = CascadeType.MERGE)
	private Set<Heat> comps;

	@OneToMany(targetEntity = Registration.class, mappedBy = "regatta", cascade = CascadeType.MERGE)
	private List<Registration> registrations;

	@Basic
	@Column(name = "Event_BoardMemberA", length = 32)
	private String boardMemberA;

	@Basic
	@Column(name = "Event_BoardMemberB", length = 32)
	private String boardMemberB;

	@Basic
	@Column(name = "Event_DefaultDistance")
	private Integer defaultDistance;

	@Basic
	@Column(name = "Event_FootLogo", length = 64)
	private String footLogo;

	@Basic
	@Column(name = "Event_HeadLogo_A", length = 64)
	private String headLogoA;

	@Basic
	@Column(name = "Event_HeadLogo_B", length = 64)
	private String headLogoB;

	@Basic
	@Column(name = "Event_SubTitle", length = 32)
	private String subTitle;

	@Basic
	@Column(name = "Event_TrackDirection", length = 3)
	private String trackDirection;

	@Basic
	@Column(name = "Event_Type", length = 1)
	private String type;

	@Basic
	@Column(name = "Event_Url", length = 64)
	private String url;

	@Basic
	@Column(name = "Event_Venue", length = 32)
	private String venue;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Event_Venue_Nation_ID_FK")
	private Nation nation;

	@OneToMany(targetEntity = Race.class, mappedBy = "regatta", cascade = CascadeType.MERGE)
	@OrderBy("raceNumber")
	private Set<Race> races;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Event_DefaultRaceMode_ID_FK")
	private RaceMode raceMode;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "Event_HeadReferee_ID_FK")
	private Referee referee;

	@ManyToMany(targetEntity = Referee.class, cascade = CascadeType.MERGE)
	@JoinTable(schema = "dbo", name = "EventReferee", joinColumns = @JoinColumn(name = "ER_Event_ID_FK"), inverseJoinColumns = @JoinColumn(name = "ER_Referee_ID_FK"))
	private Set<Referee> referees;

	@OneToMany(targetEntity = ReportInfo.class, mappedBy = "regatta", cascade = CascadeType.MERGE)
	private Set<ReportInfo> reportInfos;
}