package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="AgeClass")
@IdClass(de.regatta_hd.aquarius.db.AgeClassId.class)
public class AgeClass {
	@Basic
	@Column(name="AgeClass_Abbr", nullable=false, length=8)
	private String ageClassAbbr;

	@Basic
	@Column(name="AgeClass_AbbrSuffix", length=8)
	private String ageClassAbbrSuffix;

	@Basic
	@Column(name="AgeClass_AllowYounger")
	private byte ageClassAllowYounger;

	@Basic
	@Column(name="AgeClass_Caption", nullable=false, length=48)
	private String ageClassCaption;

	@Basic
	@Column(name="AgeClass_Gender", nullable=false, length=1)
	private String ageClassGender;

	@Id
	@Column(name="AgeClass_ID", columnDefinition="int identity")
	private int ageClassID;

	@Basic
	@Column(name="AgeClass_LW_AvgLimit")
	private int ageClassLWAvgLimit;

	@Basic
	@Column(name="AgeClass_LW_CoxLowerLimit")
	private int ageClassLWCoxLowerLimit;

	@Basic
	@Column(name="AgeClass_LW_CoxTolerance")
	private int ageClassLWCoxTolerance;

	@Basic
	@Column(name="AgeClass_LW_UpperLimit")
	private int ageClassLWUpperLimit;

	@Basic
	@Column(name="AgeClass_MaxAge")
	private byte ageClassMaxAge;

	@Basic
	@Column(name="AgeClass_MinAge")
	private byte ageClassMinAge;

	@Basic
	@Column(name="AgeClass_NumSubClasses")
	private byte ageClassNumSubClasses;

	@Basic
	@Column(name="AgeClass_Suffix", length=16)
	private String ageClassSuffix;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Offer.class, mappedBy="ageClass", cascade=CascadeType.MERGE)
	private Set<Offer> offers = new HashSet<Offer>();


	public AgeClass() {
	}

	public AgeClass(int ageClassID) {
		this.ageClassID = ageClassID;
	}

	public String getAgeClassAbbr() {
		return ageClassAbbr;
	}

	public void setAgeClassAbbr(String ageClassAbbr) {
		this.ageClassAbbr = ageClassAbbr;
	}

	public String getAgeClassAbbrSuffix() {
		return ageClassAbbrSuffix;
	}

	public void setAgeClassAbbrSuffix(String ageClassAbbrSuffix) {
		this.ageClassAbbrSuffix = ageClassAbbrSuffix;
	}

	public byte getAgeClassAllowYounger() {
		return ageClassAllowYounger;
	}

	public void setAgeClassAllowYounger(byte ageClassAllowYounger) {
		this.ageClassAllowYounger = ageClassAllowYounger;
	}

	public String getAgeClassCaption() {
		return ageClassCaption;
	}

	public void setAgeClassCaption(String ageClassCaption) {
		this.ageClassCaption = ageClassCaption;
	}

	public String getAgeClassGender() {
		return ageClassGender;
	}

	public void setAgeClassGender(String ageClassGender) {
		this.ageClassGender = ageClassGender;
	}

	public int getAgeClassID() {
		return ageClassID;
	}

	public void setAgeClassID(int ageClassID) {
		this.ageClassID = ageClassID;
	}

	public int getAgeClassLWAvgLimit() {
		return ageClassLWAvgLimit;
	}

	public void setAgeClassLWAvgLimit(int ageClassLWAvgLimit) {
		this.ageClassLWAvgLimit = ageClassLWAvgLimit;
	}

	public int getAgeClassLWCoxLowerLimit() {
		return ageClassLWCoxLowerLimit;
	}

	public void setAgeClassLWCoxLowerLimit(int ageClassLWCoxLowerLimit) {
		this.ageClassLWCoxLowerLimit = ageClassLWCoxLowerLimit;
	}

	public int getAgeClassLWCoxTolerance() {
		return ageClassLWCoxTolerance;
	}

	public void setAgeClassLWCoxTolerance(int ageClassLWCoxTolerance) {
		this.ageClassLWCoxTolerance = ageClassLWCoxTolerance;
	}

	public int getAgeClassLWUpperLimit() {
		return ageClassLWUpperLimit;
	}

	public void setAgeClassLWUpperLimit(int ageClassLWUpperLimit) {
		this.ageClassLWUpperLimit = ageClassLWUpperLimit;
	}

	public byte getAgeClassMaxAge() {
		return ageClassMaxAge;
	}

	public void setAgeClassMaxAge(byte ageClassMaxAge) {
		this.ageClassMaxAge = ageClassMaxAge;
	}

	public byte getAgeClassMinAge() {
		return ageClassMinAge;
	}

	public void setAgeClassMinAge(byte ageClassMinAge) {
		this.ageClassMinAge = ageClassMinAge;
	}

	public byte getAgeClassNumSubClasses() {
		return ageClassNumSubClasses;
	}

	public void setAgeClassNumSubClasses(byte ageClassNumSubClasses) {
		this.ageClassNumSubClasses = ageClassNumSubClasses;
	}

	public String getAgeClassSuffix() {
		return ageClassSuffix;
	}

	public void setAgeClassSuffix(String ageClassSuffix) {
		this.ageClassSuffix = ageClassSuffix;
	}

	public Set<Offer> getOffers() {
		return offers;
	}

	public void setOffers(Set<Offer> offers) {
		this.offers = offers;
	}
}