package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.AgeClass
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class AgeClassId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.AgeClass"); }
		catch(Exception e) {}
	}

	public int ageClassID;

	public AgeClassId() {
	}

	public AgeClassId(String str) {
		fromString(str);
	}

	public int getAgeClassID() {
		return ageClassID;
	}

	public void setAgeClassID(int ageClassID) {
		this.ageClassID = ageClassID;
	}

	public String toString() {
		return String.valueOf(ageClassID);
	}

	public int hashCode() {
		return ageClassID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		AgeClassId other = (AgeClassId) obj;
		return (ageClassID == other.ageClassID);
	}

	private void fromString(String str) {
		ageClassID = Integer.parseInt(str);
	}
}