package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="Athlet")
@IdClass(de.regatta_hd.aquarius.db.AthletId.class)
public class Athlet {
	@Basic
	@Column(name="Athlet_DOB", columnDefinition="datetime", nullable=false)
	private Date athletDOB;

	@Basic
	@Column(name="Athlet_ExternID_A", length=11)
	private String athletExternIDA;

	@Basic
	@Column(name="Athlet_ExternID_B", length=11)
	private String athletExternIDB;

	@Basic
	@Column(name="Athlet_ExternState")
	private byte athletExternState;

	@Basic
	@Column(name="Athlet_ExternState_B")
	private byte athletExternStateB;

	@Basic
	@Column(name="Athlet_FirstName", nullable=false, length=32)
	private String athletFirstName;

	@Basic
	@Column(name="Athlet_Gender", nullable=false, length=1)
	private String athletGender;

	@Id
	@Column(name="Athlet_ID", columnDefinition="int identity")
	private int athletID;

	@Basic
	@Column(name="Athlet_LastName", nullable=false, length=64)
	private String athletLastName;

	@Basic
	@Column(name="Athlet_SoundEx", length=5)
	private String athletSoundEx;

	@Basic
	@Column(name="Athlet_State")
	private byte athletState;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Athlet_Club_ID_FK")
	private Club club;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Crew.class, mappedBy="athlet", cascade=CascadeType.MERGE)
	private Set<Crew> crews = new HashSet<Crew>();

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Athlet_Nation_ID_FK")
	private Nation nation;


	public Athlet() {
	}

	public Athlet(int athletID) {
		this.athletID = athletID;
	}

	public Date getAthletDOB() {
		return athletDOB;
	}

	public void setAthletDOB(Date athletDOB) {
		this.athletDOB = athletDOB;
	}

	public String getAthletExternIDA() {
		return athletExternIDA;
	}

	public void setAthletExternIDA(String athletExternIDA) {
		this.athletExternIDA = athletExternIDA;
	}

	public String getAthletExternIDB() {
		return athletExternIDB;
	}

	public void setAthletExternIDB(String athletExternIDB) {
		this.athletExternIDB = athletExternIDB;
	}

	public byte getAthletExternState() {
		return athletExternState;
	}

	public void setAthletExternState(byte athletExternState) {
		this.athletExternState = athletExternState;
	}

	public byte getAthletExternStateB() {
		return athletExternStateB;
	}

	public void setAthletExternStateB(byte athletExternStateB) {
		this.athletExternStateB = athletExternStateB;
	}

	public String getAthletFirstName() {
		return athletFirstName;
	}

	public void setAthletFirstName(String athletFirstName) {
		this.athletFirstName = athletFirstName;
	}

	public String getAthletGender() {
		return athletGender;
	}

	public void setAthletGender(String athletGender) {
		this.athletGender = athletGender;
	}

	public int getAthletID() {
		return athletID;
	}

	public void setAthletID(int athletID) {
		this.athletID = athletID;
	}

	public String getAthletLastName() {
		return athletLastName;
	}

	public void setAthletLastName(String athletLastName) {
		this.athletLastName = athletLastName;
	}

	public String getAthletSoundEx() {
		return athletSoundEx;
	}

	public void setAthletSoundEx(String athletSoundEx) {
		this.athletSoundEx = athletSoundEx;
	}

	public byte getAthletState() {
		return athletState;
	}

	public void setAthletState(byte athletState) {
		this.athletState = athletState;
	}

	public Club getClub() {
		return club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public Set<Crew> getCrews() {
		return crews;
	}

	public void setCrews(Set<Crew> crews) {
		this.crews = crews;
	}

	public Nation getNation() {
		return nation;
	}

	public void setNation(Nation nation) {
		this.nation = nation;
	}
}