package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.Athlet
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class AthletId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.Athlet"); }
		catch(Exception e) {}
	}

	public int athletID;

	public AthletId() {
	}

	public AthletId(String str) {
		fromString(str);
	}

	public int getAthletID() {
		return athletID;
	}

	public void setAthletID(int athletID) {
		this.athletID = athletID;
	}

	public String toString() {
		return String.valueOf(athletID);
	}

	public int hashCode() {
		return athletID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		AthletId other = (AthletId) obj;
		return (athletID == other.athletID);
	}

	private void fromString(String str) {
		athletID = Integer.parseInt(str);
	}
}