package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.BoatClass
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class BoatClassId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.BoatClass"); }
		catch(Exception e) {}
	}

	public int boatClassID;

	public BoatClassId() {
	}

	public BoatClassId(String str) {
		fromString(str);
	}

	public int getBoatClassID() {
		return boatClassID;
	}

	public void setBoatClassID(int boatClassID) {
		this.boatClassID = boatClassID;
	}

	public String toString() {
		return String.valueOf(boatClassID);
	}

	public int hashCode() {
		return boatClassID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		BoatClassId other = (BoatClassId) obj;
		return (boatClassID == other.boatClassID);
	}

	private void fromString(String str) {
		boatClassID = Integer.parseInt(str);
	}
}