package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="BoatClass")
@IdClass(de.regatta_hd.aquarius.db.BoatClassId.class)
public class BoatClass {
	@Basic
	@Column(name="BoatClass_Abbr", nullable=false, length=8)
	private String boatClassAbbr;

	@Basic
	@Column(name="BoatClass_Caption", nullable=false, length=50)
	private String boatClassCaption;

	@Basic
	@Column(name="BoatClass_Coxed")
	private byte boatClassCoxed;

	@Id
	@Column(name="BoatClass_ID", columnDefinition="int identity")
	private int boatClassID;

	@Basic
	@Column(name="BoatClass_NumRowers")
	private byte boatClassNumRowers;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Offer.class, mappedBy="boatClass", cascade=CascadeType.MERGE)
	private Set<Offer> offers = new HashSet<Offer>();


	public BoatClass() {
	}

	public BoatClass(int boatClassID) {
		this.boatClassID = boatClassID;
	}

	public String getBoatClassAbbr() {
		return boatClassAbbr;
	}

	public void setBoatClassAbbr(String boatClassAbbr) {
		this.boatClassAbbr = boatClassAbbr;
	}

	public String getBoatClassCaption() {
		return boatClassCaption;
	}

	public void setBoatClassCaption(String boatClassCaption) {
		this.boatClassCaption = boatClassCaption;
	}

	public byte getBoatClassCoxed() {
		return boatClassCoxed;
	}

	public void setBoatClassCoxed(byte boatClassCoxed) {
		this.boatClassCoxed = boatClassCoxed;
	}

	public int getBoatClassID() {
		return boatClassID;
	}

	public void setBoatClassID(int boatClassID) {
		this.boatClassID = boatClassID;
	}

	public byte getBoatClassNumRowers() {
		return boatClassNumRowers;
	}

	public void setBoatClassNumRowers(byte boatClassNumRowers) {
		this.boatClassNumRowers = boatClassNumRowers;
	}

	public Set<Offer> getOffers() {
		return offers;
	}

	public void setOffers(Set<Offer> offers) {
		this.offers = offers;
	}
}