package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="Club")
@IdClass(de.regatta_hd.aquarius.db.ClubId.class)
public class Club {
	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Athlet.class, mappedBy="club", cascade=CascadeType.MERGE)
	private Set<Athlet> athlets = new HashSet<Athlet>();

	@Basic
	@Column(name="Club_Abbr", length=50)
	private String clubAbbr;

	@Basic
	@Column(name="Club_City", length=64)
	private String clubCity;

	@Basic
	@Column(name="Club_Discount")
	private double clubDiscount;

	@Basic
	@Column(name="Club_ExternID")
	private int clubExternID;

	@Id
	@Column(name="Club_ID", columnDefinition="int identity")
	private int clubID;

	@Basic
	@Column(name="Club_Name", length=128)
	private String clubName;

	@Basic
	@Column(name="Club_UltraAbbr", length=16)
	private String clubUltraAbbr;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Crew.class, mappedBy="club", cascade=CascadeType.MERGE)
	private Set<Crew> crews = new HashSet<Crew>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Entry.class, mappedBy="club", cascade=CascadeType.MERGE)
	private Set<Entry> entrys = new HashSet<Entry>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Event.class, mappedBy="club", cascade=CascadeType.MERGE)
	private Set<Event> events = new HashSet<Event>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Label.class, mappedBy="club", cascade=CascadeType.MERGE)
	private Set<Label> labels = new HashSet<Label>();

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Club_Nation_ID_FK")
	private Nation nation;


	public Club() {
	}

	public Club(int clubID) {
		this.clubID = clubID;
	}

	public Set<Athlet> getAthlets() {
		return athlets;
	}

	public void setAthlets(Set<Athlet> athlets) {
		this.athlets = athlets;
	}

	public String getClubAbbr() {
		return clubAbbr;
	}

	public void setClubAbbr(String clubAbbr) {
		this.clubAbbr = clubAbbr;
	}

	public String getClubCity() {
		return clubCity;
	}

	public void setClubCity(String clubCity) {
		this.clubCity = clubCity;
	}

	public double getClubDiscount() {
		return clubDiscount;
	}

	public void setClubDiscount(double clubDiscount) {
		this.clubDiscount = clubDiscount;
	}

	public int getClubExternID() {
		return clubExternID;
	}

	public void setClubExternID(int clubExternID) {
		this.clubExternID = clubExternID;
	}

	public int getClubID() {
		return clubID;
	}

	public void setClubID(int clubID) {
		this.clubID = clubID;
	}

	public String getClubName() {
		return clubName;
	}

	public void setClubName(String clubName) {
		this.clubName = clubName;
	}

	public String getClubUltraAbbr() {
		return clubUltraAbbr;
	}

	public void setClubUltraAbbr(String clubUltraAbbr) {
		this.clubUltraAbbr = clubUltraAbbr;
	}

	public Set<Crew> getCrews() {
		return crews;
	}

	public void setCrews(Set<Crew> crews) {
		this.crews = crews;
	}

	public Set<Entry> getEntrys() {
		return entrys;
	}

	public void setEntrys(Set<Entry> entrys) {
		this.entrys = entrys;
	}

	public Set<Event> getEvents() {
		return events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	public Set<Label> getLabels() {
		return labels;
	}

	public void setLabels(Set<Label> labels) {
		this.labels = labels;
	}

	public Nation getNation() {
		return nation;
	}

	public void setNation(Nation nation) {
		this.nation = nation;
	}
}