package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.Club
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class ClubId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.Club"); }
		catch(Exception e) {}
	}

	public int clubID;

	public ClubId() {
	}

	public ClubId(String str) {
		fromString(str);
	}

	public int getClubID() {
		return clubID;
	}

	public void setClubID(int clubID) {
		this.clubID = clubID;
	}

	public String toString() {
		return String.valueOf(clubID);
	}

	public int hashCode() {
		return clubID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		ClubId other = (ClubId) obj;
		return (clubID == other.clubID);
	}

	private void fromString(String str) {
		clubID = Integer.parseInt(str);
	}
}