package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="CompEntries")
@IdClass(de.regatta_hd.aquarius.db.CompEntriesId.class)
public class CompEntries {
	@Basic
	@Column(name="CE_Lane")
	private short cELane;

	@Id
	@Column(name="CE_ID", columnDefinition="int identity")
	private int ceId;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="CE_Comp_ID_FK")
	private Comp comp;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="CE_Entry_ID_FK", nullable=false)
	private Entry entry;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Result.class, mappedBy="compEntries", cascade=CascadeType.MERGE)
	private Set<Result> results = new HashSet<Result>();


	public CompEntries() {
	}

	public CompEntries(int ceId) {
		this.ceId = ceId;
	}

	public short getcELane() {
		return cELane;
	}

	public void setcELane(short cELane) {
		this.cELane = cELane;
	}

	public int getCeId() {
		return ceId;
	}

	public void setCeId(int ceId) {
		this.ceId = ceId;
	}

	public Comp getComp() {
		return comp;
	}

	public void setComp(Comp comp) {
		this.comp = comp;
	}

	public Entry getEntry() {
		return entry;
	}

	public void setEntry(Entry entry) {
		this.entry = entry;
	}

	public Set<Result> getResults() {
		return results;
	}

	public void setResults(Set<Result> results) {
		this.results = results;
	}
}