package de.regatta_hd.aquarius.db;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="CompReferee")
@IdClass(de.regatta_hd.aquarius.db.CompRefereeId.class)
public class CompReferee {
	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="CompReferee_Comp_ID_FK", nullable=false)
	private Comp comp;

	@Id
	@Column(name="CompReferee_ID", columnDefinition="int identity")
	private int compRefereeID;

	@Basic
	@Column(name="CompReferee_Role", length=1)
	private String compRefereeRole;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="CompReferee_Referee_ID_FK", nullable=false)
	private Referee referee;


	public CompReferee() {
	}

	public CompReferee(int compRefereeID) {
		this.compRefereeID = compRefereeID;
	}

	public Comp getComp() {
		return comp;
	}

	public void setComp(Comp comp) {
		this.comp = comp;
	}

	public int getCompRefereeID() {
		return compRefereeID;
	}

	public void setCompRefereeID(int compRefereeID) {
		this.compRefereeID = compRefereeID;
	}

	public String getCompRefereeRole() {
		return compRefereeRole;
	}

	public void setCompRefereeRole(String compRefereeRole) {
		this.compRefereeRole = compRefereeRole;
	}

	public Referee getReferee() {
		return referee;
	}

	public void setReferee(Referee referee) {
		this.referee = referee;
	}
}