package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="Comp")
@IdClass(de.regatta_hd.aquarius.db.CompId.class)
public class Comp {
	@Basic
	@Column(name="Comp_Cancelled")
	private boolean compCancelled;

	@Basic
	@Column(name="Comp_DateTime", columnDefinition="datetime")
	private Date compDateTime;

	@Basic
	@Column(name="Comp_Dummy")
	private boolean compDummy;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.CompEntries.class, mappedBy="comp", cascade=CascadeType.MERGE)
	private Set<CompEntries> compEntries = new HashSet<CompEntries>();

	@Basic
	@Column(name="Comp_GroupValue")
	private short compGroupValue;

	@Basic
	@Column(name="Comp_HeatNumber")
	private short compHeatNumber;

	@Id
	@Column(name="Comp_ID", columnDefinition="int identity")
	private int compID;

	@Basic
	@Column(name="Comp_Label", length=32)
	private String compLabel;

	@Basic
	@Column(name="Comp_Locked")
	private boolean compLocked;

	@Basic
	@Column(name="Comp_Number")
	private short compNumber;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.CompReferee.class, mappedBy="comp", cascade=CascadeType.MERGE)
	private Set<CompReferee> compReferees = new HashSet<CompReferee>();

	@Basic
	@Column(name="Comp_Round")
	private short compRound;

	@Basic
	@Column(name="Comp_RoundCode", length=8)
	private String compRoundCode;

	@Basic
	@Column(name="Comp_State")
	private byte compState;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Comp_Event_ID_FK", nullable=false)
	private Event event;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Comp_Race_ID_FK")
	private Offer offer;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Comp_RMDetail_ID_FK")
	private RaceModeDetail raceModeDetail;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.ReportInfo.class, mappedBy="comp", cascade=CascadeType.MERGE)
	private Set<ReportInfo> reportInfos = new HashSet<ReportInfo>();


	public Comp() {
	}

	public Comp(int compID) {
		this.compID = compID;
	}

	public boolean isCompCancelled() {
		return compCancelled;
	}

	public void setCompCancelled(boolean compCancelled) {
		this.compCancelled = compCancelled;
	}

	public Date getCompDateTime() {
		return compDateTime;
	}

	public void setCompDateTime(Date compDateTime) {
		this.compDateTime = compDateTime;
	}

	public boolean isCompDummy() {
		return compDummy;
	}

	public void setCompDummy(boolean compDummy) {
		this.compDummy = compDummy;
	}

	public Set<CompEntries> getCompEntries() {
		return compEntries;
	}

	public void setCompEntries(Set<CompEntries> compEntries) {
		this.compEntries = compEntries;
	}

	public short getCompGroupValue() {
		return compGroupValue;
	}

	public void setCompGroupValue(short compGroupValue) {
		this.compGroupValue = compGroupValue;
	}

	public short getCompHeatNumber() {
		return compHeatNumber;
	}

	public void setCompHeatNumber(short compHeatNumber) {
		this.compHeatNumber = compHeatNumber;
	}

	public int getCompID() {
		return compID;
	}

	public void setCompID(int compID) {
		this.compID = compID;
	}

	public String getCompLabel() {
		return compLabel;
	}

	public void setCompLabel(String compLabel) {
		this.compLabel = compLabel;
	}

	public boolean isCompLocked() {
		return compLocked;
	}

	public void setCompLocked(boolean compLocked) {
		this.compLocked = compLocked;
	}

	public short getCompNumber() {
		return compNumber;
	}

	public void setCompNumber(short compNumber) {
		this.compNumber = compNumber;
	}

	public Set<CompReferee> getCompReferees() {
		return compReferees;
	}

	public void setCompReferees(Set<CompReferee> compReferees) {
		this.compReferees = compReferees;
	}

	public short getCompRound() {
		return compRound;
	}

	public void setCompRound(short compRound) {
		this.compRound = compRound;
	}

	public String getCompRoundCode() {
		return compRoundCode;
	}

	public void setCompRoundCode(String compRoundCode) {
		this.compRoundCode = compRoundCode;
	}

	public byte getCompState() {
		return compState;
	}

	public void setCompState(byte compState) {
		this.compState = compState;
	}

	public Event getEvent() {
		return event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Offer getOffer() {
		return offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	public RaceModeDetail getRaceModeDetail() {
		return raceModeDetail;
	}

	public void setRaceModeDetail(RaceModeDetail raceModeDetail) {
		this.raceModeDetail = raceModeDetail;
	}

	public Set<ReportInfo> getReportInfos() {
		return reportInfos;
	}

	public void setReportInfos(Set<ReportInfo> reportInfos) {
		this.reportInfos = reportInfos;
	}
}