package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.CompReferee
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CompRefereeId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.CompReferee"); }
		catch(Exception e) {}
	}

	public int compRefereeID;

	public CompRefereeId() {
	}

	public CompRefereeId(String str) {
		fromString(str);
	}

	public int getCompRefereeID() {
		return compRefereeID;
	}

	public void setCompRefereeID(int compRefereeID) {
		this.compRefereeID = compRefereeID;
	}

	public String toString() {
		return String.valueOf(compRefereeID);
	}

	public int hashCode() {
		return compRefereeID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		CompRefereeId other = (CompRefereeId) obj;
		return (compRefereeID == other.compRefereeID);
	}

	private void fromString(String str) {
		compRefereeID = Integer.parseInt(str);
	}
}