package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.CompEntries
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CompEntriesId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.CompEntries"); }
		catch(Exception e) {}
	}

	public int ceId;

	public CompEntriesId() {
	}

	public CompEntriesId(String str) {
		fromString(str);
	}

	public int getCeId() {
		return ceId;
	}

	public void setCeId(int ceId) {
		this.ceId = ceId;
	}

	public String toString() {
		return String.valueOf(ceId);
	}

	public int hashCode() {
		return ceId;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		CompEntriesId other = (CompEntriesId) obj;
		return (ceId == other.ceId);
	}

	private void fromString(String str) {
		ceId = Integer.parseInt(str);
	}
}