package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.Comp
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CompId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.Comp"); }
		catch(Exception e) {}
	}

	public int compID;

	public CompId() {
	}

	public CompId(String str) {
		fromString(str);
	}

	public int getCompID() {
		return compID;
	}

	public void setCompID(int compID) {
		this.compID = compID;
	}

	public String toString() {
		return String.valueOf(compID);
	}

	public int hashCode() {
		return compID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		CompId other = (CompId) obj;
		return (compID == other.compID);
	}

	private void fromString(String str) {
		compID = Integer.parseInt(str);
	}
}