package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.Crew
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CrewId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.Crew"); }
		catch(Exception e) {}
	}

	public int crewID;

	public CrewId() {
	}

	public CrewId(String str) {
		fromString(str);
	}

	public int getCrewID() {
		return crewID;
	}

	public void setCrewID(int crewID) {
		this.crewID = crewID;
	}

	public String toString() {
		return String.valueOf(crewID);
	}

	public int hashCode() {
		return crewID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		CrewId other = (CrewId) obj;
		return (crewID == other.crewID);
	}

	private void fromString(String str) {
		crewID = Integer.parseInt(str);
	}
}