package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="Cup")
@IdClass(de.regatta_hd.aquarius.db.CupId.class)
public class Cup {
	@Basic
	@Column(columnDefinition="nvarchar", length=32)
	private String caption;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Parent_ID")
	private Cup cup;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="PointTable_ID_FK")
	private CupPointTable cupPointTable;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Cup.class, mappedBy="cup", cascade=CascadeType.MERGE)
	private Set<Cup> cups = new HashSet<Cup>();

	@Id
	@Column(columnDefinition="int identity")
	private int id;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Race_ID_FK")
	private Offer offer;


	public Cup() {
	}

	public Cup(int id) {
		this.id = id;
	}

	public String getCaption() {
		return caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	public Cup getCup() {
		return cup;
	}

	public void setCup(Cup cup) {
		this.cup = cup;
	}

	public CupPointTable getCupPointTable() {
		return cupPointTable;
	}

	public void setCupPointTable(CupPointTable cupPointTable) {
		this.cupPointTable = cupPointTable;
	}

	public Set<Cup> getCups() {
		return cups;
	}

	public void setCups(Set<Cup> cups) {
		this.cups = cups;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Offer getOffer() {
		return offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}
}