package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.Cup
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CupId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.Cup"); }
		catch(Exception e) {}
	}

	public int id;

	public CupId() {
	}

	public CupId(String str) {
		fromString(str);
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String toString() {
		return String.valueOf(id);
	}

	public int hashCode() {
		return id;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		CupId other = (CupId) obj;
		return (id == other.id);
	}

	private void fromString(String str) {
		id = Integer.parseInt(str);
	}
}