package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.CupPointTable
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CupPointTableId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.CupPointTable"); }
		catch(Exception e) {}
	}

	public int id;

	public CupPointTableId() {
	}

	public CupPointTableId(String str) {
		fromString(str);
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String toString() {
		return String.valueOf(id);
	}

	public int hashCode() {
		return id;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		CupPointTableId other = (CupPointTableId) obj;
		return (id == other.id);
	}

	private void fromString(String str) {
		id = Integer.parseInt(str);
	}
}