package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="CupPointTable")
@IdClass(de.regatta_hd.aquarius.db.CupPointTableId.class)
public class CupPointTable {
	@Basic
	@Column(columnDefinition="nvarchar", length=32)
	private String caption;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Parent_ID")
	private CupPointTable cupPointTable;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.CupPointTable.class, mappedBy="cupPointTable", cascade=CascadeType.MERGE)
	private Set<CupPointTable> cupPointTables = new HashSet<CupPointTable>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Cup.class, mappedBy="cupPointTable", cascade=CascadeType.MERGE)
	private Set<Cup> cups = new HashSet<Cup>();

	@Id
	@Column(columnDefinition="int identity")
	private int id;

	@Basic
	private short lap;

	@Basic
	private double points;

	@Basic
	private byte rank;

	@Basic
	private short round;


	public CupPointTable() {
	}

	public CupPointTable(int id) {
		this.id = id;
	}

	public String getCaption() {
		return caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	public CupPointTable getCupPointTable() {
		return cupPointTable;
	}

	public void setCupPointTable(CupPointTable cupPointTable) {
		this.cupPointTable = cupPointTable;
	}

	public Set<CupPointTable> getCupPointTables() {
		return cupPointTables;
	}

	public void setCupPointTables(Set<CupPointTable> cupPointTables) {
		this.cupPointTables = cupPointTables;
	}

	public Set<Cup> getCups() {
		return cups;
	}

	public void setCups(Set<Cup> cups) {
		this.cups = cups;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public short getLap() {
		return lap;
	}

	public void setLap(short lap) {
		this.lap = lap;
	}

	public double getPoints() {
		return points;
	}

	public void setPoints(double points) {
		this.points = points;
	}

	public byte getRank() {
		return rank;
	}

	public void setRank(byte rank) {
		this.rank = rank;
	}

	public short getRound() {
		return round;
	}

	public void setRound(short round) {
		this.round = round;
	}
}