package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.EntryLabel
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class EntryLabelId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.EntryLabel"); }
		catch(Exception e) {}
	}

	public int elId;

	public EntryLabelId() {
	}

	public EntryLabelId(String str) {
		fromString(str);
	}

	public int getElId() {
		return elId;
	}

	public void setElId(int elId) {
		this.elId = elId;
	}

	public String toString() {
		return String.valueOf(elId);
	}

	public int hashCode() {
		return elId;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		EntryLabelId other = (EntryLabelId) obj;
		return (elId == other.elId);
	}

	private void fromString(String str) {
		elId = Integer.parseInt(str);
	}
}