package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="Entry")
@IdClass(de.regatta_hd.aquarius.db.EntryId.class)
public class Entry {
	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Entry_OwnerClub_ID_FK", nullable=false)
	private Club club;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.CompEntries.class, mappedBy="entry", cascade=CascadeType.MERGE)
	private Set<CompEntries> compEntries = new HashSet<CompEntries>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Crew.class, mappedBy="entry", cascade=CascadeType.MERGE)
	private Set<Crew> crews = new HashSet<Crew>();

	@Basic
	@Column(name="Entry_Bib")
	private short entryBib;

	@Basic
	@Column(name="Entry_BoatNumber")
	private short entryBoatNumber;

	@Basic
	@Column(name="Entry_CancelValue")
	private byte entryCancelValue;

	@Basic
	@Column(name="Entry_Comment", length=50)
	private String entryComment;

	@Basic
	@Column(name="Entry_ExternID")
	private int entryExternID;

	@Basic
	@Column(name="Entry_GroupValue")
	private short entryGroupValue;

	@Id
	@Column(name="Entry_ID", columnDefinition="int identity")
	private int entryID;

	@Basic
	@Column(name="Entry_IsLate")
	private boolean entryIsLate;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.EntryLabel.class, mappedBy="entry", cascade=CascadeType.MERGE)
	private Set<EntryLabel> entryLabels = new HashSet<EntryLabel>();

	@Basic
	@Column(name="Entry_Note", length=128)
	private String entryNote;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Entry_Event_ID_FK", nullable=false)
	private Event event;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Entry_ManualLabel_ID_FK")
	private Label label;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Entry_Race_ID_FK", nullable=false)
	private Offer offer;


	public Entry() {
	}

	public Entry(int entryID) {
		this.entryID = entryID;
	}

	public Club getClub() {
		return club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public Set<CompEntries> getCompEntries() {
		return compEntries;
	}

	public void setCompEntries(Set<CompEntries> compEntries) {
		this.compEntries = compEntries;
	}

	public Set<Crew> getCrews() {
		return crews;
	}

	public void setCrews(Set<Crew> crews) {
		this.crews = crews;
	}

	public short getEntryBib() {
		return entryBib;
	}

	public void setEntryBib(short entryBib) {
		this.entryBib = entryBib;
	}

	public short getEntryBoatNumber() {
		return entryBoatNumber;
	}

	public void setEntryBoatNumber(short entryBoatNumber) {
		this.entryBoatNumber = entryBoatNumber;
	}

	public byte getEntryCancelValue() {
		return entryCancelValue;
	}

	public void setEntryCancelValue(byte entryCancelValue) {
		this.entryCancelValue = entryCancelValue;
	}

	public String getEntryComment() {
		return entryComment;
	}

	public void setEntryComment(String entryComment) {
		this.entryComment = entryComment;
	}

	public int getEntryExternID() {
		return entryExternID;
	}

	public void setEntryExternID(int entryExternID) {
		this.entryExternID = entryExternID;
	}

	public short getEntryGroupValue() {
		return entryGroupValue;
	}

	public void setEntryGroupValue(short entryGroupValue) {
		this.entryGroupValue = entryGroupValue;
	}

	public int getEntryID() {
		return entryID;
	}

	public void setEntryID(int entryID) {
		this.entryID = entryID;
	}

	public boolean isEntryIsLate() {
		return entryIsLate;
	}

	public void setEntryIsLate(boolean entryIsLate) {
		this.entryIsLate = entryIsLate;
	}

	public Set<EntryLabel> getEntryLabels() {
		return entryLabels;
	}

	public void setEntryLabels(Set<EntryLabel> entryLabels) {
		this.entryLabels = entryLabels;
	}

	public String getEntryNote() {
		return entryNote;
	}

	public void setEntryNote(String entryNote) {
		this.entryNote = entryNote;
	}

	public Event getEvent() {
		return event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Label getLabel() {
		return label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

	public Offer getOffer() {
		return offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}
}