package de.regatta_hd.aquarius.db;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="EntryLabel")
@IdClass(de.regatta_hd.aquarius.db.EntryLabelId.class)
public class EntryLabel {
	@Basic
	@Column(name="EL_IsClubMultiNOC")
	private boolean eLIsClubMultiNOC;

	@Basic
	@Column(name="EL_IsCrewClubMultiNOC")
	private boolean eLIsCrewClubMultiNOC;

	@Basic
	@Column(name="EL_RoundFrom")
	private short eLRoundFrom;

	@Basic
	@Column(name="EL_RoundTo")
	private short eLRoundTo;

	@Id
	@Column(name="EL_ID", columnDefinition="int identity")
	private int elId;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="EL_Entry_ID_FK", nullable=false)
	private Entry entry;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="EL_Label_ID_FK", nullable=false)
	private Label label;


	public EntryLabel() {
	}

	public EntryLabel(int elId) {
		this.elId = elId;
	}

	public boolean iseLIsClubMultiNOC() {
		return eLIsClubMultiNOC;
	}

	public void seteLIsClubMultiNOC(boolean eLIsClubMultiNOC) {
		this.eLIsClubMultiNOC = eLIsClubMultiNOC;
	}

	public boolean iseLIsCrewClubMultiNOC() {
		return eLIsCrewClubMultiNOC;
	}

	public void seteLIsCrewClubMultiNOC(boolean eLIsCrewClubMultiNOC) {
		this.eLIsCrewClubMultiNOC = eLIsCrewClubMultiNOC;
	}

	public short geteLRoundFrom() {
		return eLRoundFrom;
	}

	public void seteLRoundFrom(short eLRoundFrom) {
		this.eLRoundFrom = eLRoundFrom;
	}

	public short geteLRoundTo() {
		return eLRoundTo;
	}

	public void seteLRoundTo(short eLRoundTo) {
		this.eLRoundTo = eLRoundTo;
	}

	public int getElId() {
		return elId;
	}

	public void setElId(int elId) {
		this.elId = elId;
	}

	public Entry getEntry() {
		return entry;
	}

	public void setEntry(Entry entry) {
		this.entry = entry;
	}

	public Label getLabel() {
		return label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}
}