package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.Entry
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class EntryId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.Entry"); }
		catch(Exception e) {}
	}

	public int entryID;

	public EntryId() {
	}

	public EntryId(String str) {
		fromString(str);
	}

	public int getEntryID() {
		return entryID;
	}

	public void setEntryID(int entryID) {
		this.entryID = entryID;
	}

	public String toString() {
		return String.valueOf(entryID);
	}

	public int hashCode() {
		return entryID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		EntryId other = (EntryId) obj;
		return (entryID == other.entryID);
	}

	private void fromString(String str) {
		entryID = Integer.parseInt(str);
	}
}