package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.Event
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class EventId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.Event"); }
		catch(Exception e) {}
	}

	public int eventID;

	public EventId() {
	}

	public EventId(String str) {
		fromString(str);
	}

	public int getEventID() {
		return eventID;
	}

	public void setEventID(int eventID) {
		this.eventID = eventID;
	}

	public String toString() {
		return String.valueOf(eventID);
	}

	public int hashCode() {
		return eventID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		EventId other = (EventId) obj;
		return (eventID == other.eventID);
	}

	private void fromString(String str) {
		eventID = Integer.parseInt(str);
	}
}