package de.regatta_hd.aquarius.db;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="EventReferee")
@IdClass(de.regatta_hd.aquarius.db.EventRefereeId.class)
public class EventReferee {
	@Id
	@Column(name="ER_Event_ID_FK")
	private int eREventIDFK;

	@Id
	@Column(name="ER_Referee_ID_FK")
	private int eRRefereeIDFK;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="ER_Event_ID_FK")
	private Event event;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="ER_Referee_ID_FK")
	private Referee referee;


	public EventReferee() {
	}

	public EventReferee(int eREventIDFK, int eRRefereeIDFK) {
		this.eREventIDFK = eREventIDFK;
		this.eRRefereeIDFK = eRRefereeIDFK;
	}

	public int geteREventIDFK() {
		return eREventIDFK;
	}

	public void seteREventIDFK(int eREventIDFK) {
		this.eREventIDFK = eREventIDFK;
	}

	public int geteRRefereeIDFK() {
		return eRRefereeIDFK;
	}

	public void seteRRefereeIDFK(int eRRefereeIDFK) {
		this.eRRefereeIDFK = eRRefereeIDFK;
	}

	public Event getEvent() {
		return event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Referee getReferee() {
		return referee;
	}

	public void setReferee(Referee referee) {
		this.referee = referee;
	}
}