package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.Label
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class LabelId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.Label"); }
		catch(Exception e) {}
	}

	public int labelID;

	public LabelId() {
	}

	public LabelId(String str) {
		fromString(str);
	}

	public int getLabelID() {
		return labelID;
	}

	public void setLabelID(int labelID) {
		this.labelID = labelID;
	}

	public String toString() {
		return String.valueOf(labelID);
	}

	public int hashCode() {
		return labelID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		LabelId other = (LabelId) obj;
		return (labelID == other.labelID);
	}

	private void fromString(String str) {
		labelID = Integer.parseInt(str);
	}
}