package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="Label")
@IdClass(de.regatta_hd.aquarius.db.LabelId.class)
public class Label {
	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Label_Club_ID_FK")
	private Club club;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.EntryLabel.class, mappedBy="label", cascade=CascadeType.MERGE)
	private Set<EntryLabel> entryLabels = new HashSet<EntryLabel>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Entry.class, mappedBy="label", cascade=CascadeType.MERGE)
	private Set<Entry> entrys = new HashSet<Entry>();

	@Id
	@Column(name="Label_ID", columnDefinition="int identity")
	private int labelID;

	@Basic
	@Column(name="Label_IsTeam")
	private boolean labelIsTeam;

	@Basic
	@Column(name="Label_Long", nullable=false, length=512)
	private String labelLong;

	@Basic
	@Column(name="Label_Short", nullable=false, length=256)
	private String labelShort;


	public Label() {
	}

	public Label(int labelID) {
		this.labelID = labelID;
	}

	public Club getClub() {
		return club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public Set<EntryLabel> getEntryLabels() {
		return entryLabels;
	}

	public void setEntryLabels(Set<EntryLabel> entryLabels) {
		this.entryLabels = entryLabels;
	}

	public Set<Entry> getEntrys() {
		return entrys;
	}

	public void setEntrys(Set<Entry> entrys) {
		this.entrys = entrys;
	}

	public int getLabelID() {
		return labelID;
	}

	public void setLabelID(int labelID) {
		this.labelID = labelID;
	}

	public boolean isLabelIsTeam() {
		return labelIsTeam;
	}

	public void setLabelIsTeam(boolean labelIsTeam) {
		this.labelIsTeam = labelIsTeam;
	}

	public String getLabelLong() {
		return labelLong;
	}

	public void setLabelLong(String labelLong) {
		this.labelLong = labelLong;
	}

	public String getLabelShort() {
		return labelShort;
	}

	public void setLabelShort(String labelShort) {
		this.labelShort = labelShort;
	}
}