package de.regatta_hd.aquarius.db;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="MetaData")
@IdClass(de.regatta_hd.aquarius.db.MetaDataId.class)
public class MetaData {
	@Id
	@Column(name="MetaData_Key", length=32)
	private String metaDataKey;

	@Basic
	@Column(name="MetaData_Value", length=32)
	private String metaDataValue;


	public MetaData() {
	}

	public MetaData(String metaDataKey) {
		this.metaDataKey = metaDataKey;
	}

	public String getMetaDataKey() {
		return metaDataKey;
	}

	public void setMetaDataKey(String metaDataKey) {
		this.metaDataKey = metaDataKey;
	}

	public String getMetaDataValue() {
		return metaDataValue;
	}

	public void setMetaDataValue(String metaDataValue) {
		this.metaDataValue = metaDataValue;
	}
}