package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.MetaData
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class MetaDataId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.MetaData"); }
		catch(Exception e) {}
	}

	public String metaDataKey;

	public MetaDataId() {
	}

	public MetaDataId(String str) {
		fromString(str);
	}

	public String getMetaDataKey() {
		return metaDataKey;
	}

	public void setMetaDataKey(String metaDataKey) {
		this.metaDataKey = metaDataKey;
	}

	public String toString() {
		return metaDataKey;
	}

	public int hashCode() {
		return ((metaDataKey == null) ? 0 : metaDataKey.hashCode());
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		MetaDataId other = (MetaDataId) obj;
		return ((metaDataKey == null && other.metaDataKey == null)
			|| (metaDataKey != null && metaDataKey.equals(other.metaDataKey)));
	}

	private void fromString(String str) {
		if("null".equals(str))
			metaDataKey = null;
		else
			metaDataKey = str;
	}
}