package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.Nation
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class NationId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.Nation"); }
		catch(Exception e) {}
	}

	public int nationID;

	public NationId() {
	}

	public NationId(String str) {
		fromString(str);
	}

	public int getNationID() {
		return nationID;
	}

	public void setNationID(int nationID) {
		this.nationID = nationID;
	}

	public String toString() {
		return String.valueOf(nationID);
	}

	public int hashCode() {
		return nationID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		NationId other = (NationId) obj;
		return (nationID == other.nationID);
	}

	private void fromString(String str) {
		nationID = Integer.parseInt(str);
	}
}