package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="Nation")
@IdClass(de.regatta_hd.aquarius.db.NationId.class)
public class Nation {
	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Athlet.class, mappedBy="nation", cascade=CascadeType.MERGE)
	private Set<Athlet> athlets = new HashSet<Athlet>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Club.class, mappedBy="nation", cascade=CascadeType.MERGE)
	private Set<Club> clubs = new HashSet<Club>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Event.class, mappedBy="nation", cascade=CascadeType.MERGE)
	private Set<Event> events = new HashSet<Event>();

	@Id
	@Column(name="Nation_ID", columnDefinition="int identity")
	private int nationID;

	@Basic
	@Column(name="Nation_IOC_Code", length=5)
	private String nationIOCCode;

	@Basic
	@Column(name="Nation_Name", length=64)
	private String nationName;

	@Basic
	@Column(name="Nation_Name_German", length=64)
	private String nationNameGerman;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Referee.class, mappedBy="nation", cascade=CascadeType.MERGE)
	private Set<Referee> referees = new HashSet<Referee>();


	public Nation() {
	}

	public Nation(int nationID) {
		this.nationID = nationID;
	}

	public Set<Athlet> getAthlets() {
		return athlets;
	}

	public void setAthlets(Set<Athlet> athlets) {
		this.athlets = athlets;
	}

	public Set<Club> getClubs() {
		return clubs;
	}

	public void setClubs(Set<Club> clubs) {
		this.clubs = clubs;
	}

	public Set<Event> getEvents() {
		return events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	public int getNationID() {
		return nationID;
	}

	public void setNationID(int nationID) {
		this.nationID = nationID;
	}

	public String getNationIOCCode() {
		return nationIOCCode;
	}

	public void setNationIOCCode(String nationIOCCode) {
		this.nationIOCCode = nationIOCCode;
	}

	public String getNationName() {
		return nationName;
	}

	public void setNationName(String nationName) {
		this.nationName = nationName;
	}

	public String getNationNameGerman() {
		return nationNameGerman;
	}

	public void setNationNameGerman(String nationNameGerman) {
		this.nationNameGerman = nationNameGerman;
	}

	public Set<Referee> getReferees() {
		return referees;
	}

	public void setReferees(Set<Referee> referees) {
		this.referees = referees;
	}
}