package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="Offer")
@IdClass(de.regatta_hd.aquarius.db.OfferId.class)
public class Offer {
	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Offer_AgeClass_ID_FK", nullable=false)
	private AgeClass ageClass;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Offer_BoatClass_ID_FK", nullable=false)
	private BoatClass boatClass;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Comp.class, mappedBy="offer", cascade=CascadeType.MERGE)
	private Set<Comp> comps = new HashSet<Comp>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Cup.class, mappedBy="offer", cascade=CascadeType.MERGE)
	private Set<Cup> cups = new HashSet<Cup>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Entry.class, mappedBy="offer", cascade=CascadeType.MERGE)
	private Set<Entry> entrys = new HashSet<Entry>();

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Offer_Event_ID_FK", nullable=false)
	private Event event;

	@Basic
	@Column(name="Offer_BibSeed")
	private short offerBibSeed;

	@Basic
	@Column(name="Offer_Cancelled")
	private boolean offerCancelled;

	@Basic
	@Column(name="Offer_Comment", length=32)
	private String offerComment;

	@Basic
	@Column(name="Offer_Distance")
	private short offerDistance;

	@Basic
	@Column(name="Offer_Driven")
	private boolean offerDriven;

	@Basic
	@Column(name="Offer_EventDay")
	private int offerEventDay;

	@Basic
	@Column(name="Offer_Fee", columnDefinition="smallmoney")
	private double offerFee;

	@Basic
	@Column(name="Offer_ForceDriven")
	private boolean offerForceDriven;

	@Basic
	@Column(name="Offer_GroupMode")
	private byte offerGroupMode;

	@Id
	@Column(name="Offer_ID", columnDefinition="int identity")
	private int offerID;

	@Basic
	@Column(name="Offer_IsLightweight")
	private boolean offerIsLightweight;

	@Basic
	@Column(name="Offer_LongLabel", length=64)
	private String offerLongLabel;

	@Basic
	@Column(name="Offer_Prize", length=128)
	private String offerPrize;

	@Basic
	@Column(name="Offer_RaceNumber", nullable=false, length=8)
	private String offerRaceNumber;

	@Basic
	@Column(name="Offer_RaceType")
	private byte offerRaceType;

	@Basic
	@Column(name="Offer_ShortLabel", length=32)
	private String offerShortLabel;

	@Basic
	@Column(name="Offer_SortValue")
	private int offerSortValue;

	@Basic
	@Column(name="Offer_Splits")
	private int offerSplits;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Offer_RaceMode_ID_FK")
	private RaceMode raceMode;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.ReportInfo.class, mappedBy="offer", cascade=CascadeType.MERGE)
	private Set<ReportInfo> reportInfos = new HashSet<ReportInfo>();


	public Offer() {
	}

	public Offer(int offerID) {
		this.offerID = offerID;
	}

	public AgeClass getAgeClass() {
		return ageClass;
	}

	public void setAgeClass(AgeClass ageClass) {
		this.ageClass = ageClass;
	}

	public BoatClass getBoatClass() {
		return boatClass;
	}

	public void setBoatClass(BoatClass boatClass) {
		this.boatClass = boatClass;
	}

	public Set<Comp> getComps() {
		return comps;
	}

	public void setComps(Set<Comp> comps) {
		this.comps = comps;
	}

	public Set<Cup> getCups() {
		return cups;
	}

	public void setCups(Set<Cup> cups) {
		this.cups = cups;
	}

	public Set<Entry> getEntrys() {
		return entrys;
	}

	public void setEntrys(Set<Entry> entrys) {
		this.entrys = entrys;
	}

	public Event getEvent() {
		return event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public short getOfferBibSeed() {
		return offerBibSeed;
	}

	public void setOfferBibSeed(short offerBibSeed) {
		this.offerBibSeed = offerBibSeed;
	}

	public boolean isOfferCancelled() {
		return offerCancelled;
	}

	public void setOfferCancelled(boolean offerCancelled) {
		this.offerCancelled = offerCancelled;
	}

	public String getOfferComment() {
		return offerComment;
	}

	public void setOfferComment(String offerComment) {
		this.offerComment = offerComment;
	}

	public short getOfferDistance() {
		return offerDistance;
	}

	public void setOfferDistance(short offerDistance) {
		this.offerDistance = offerDistance;
	}

	public boolean isOfferDriven() {
		return offerDriven;
	}

	public void setOfferDriven(boolean offerDriven) {
		this.offerDriven = offerDriven;
	}

	public int getOfferEventDay() {
		return offerEventDay;
	}

	public void setOfferEventDay(int offerEventDay) {
		this.offerEventDay = offerEventDay;
	}

	public double getOfferFee() {
		return offerFee;
	}

	public void setOfferFee(double offerFee) {
		this.offerFee = offerFee;
	}

	public boolean isOfferForceDriven() {
		return offerForceDriven;
	}

	public void setOfferForceDriven(boolean offerForceDriven) {
		this.offerForceDriven = offerForceDriven;
	}

	public byte getOfferGroupMode() {
		return offerGroupMode;
	}

	public void setOfferGroupMode(byte offerGroupMode) {
		this.offerGroupMode = offerGroupMode;
	}

	public int getOfferID() {
		return offerID;
	}

	public void setOfferID(int offerID) {
		this.offerID = offerID;
	}

	public boolean isOfferIsLightweight() {
		return offerIsLightweight;
	}

	public void setOfferIsLightweight(boolean offerIsLightweight) {
		this.offerIsLightweight = offerIsLightweight;
	}

	public String getOfferLongLabel() {
		return offerLongLabel;
	}

	public void setOfferLongLabel(String offerLongLabel) {
		this.offerLongLabel = offerLongLabel;
	}

	public String getOfferPrize() {
		return offerPrize;
	}

	public void setOfferPrize(String offerPrize) {
		this.offerPrize = offerPrize;
	}

	public String getOfferRaceNumber() {
		return offerRaceNumber;
	}

	public void setOfferRaceNumber(String offerRaceNumber) {
		this.offerRaceNumber = offerRaceNumber;
	}

	public byte getOfferRaceType() {
		return offerRaceType;
	}

	public void setOfferRaceType(byte offerRaceType) {
		this.offerRaceType = offerRaceType;
	}

	public String getOfferShortLabel() {
		return offerShortLabel;
	}

	public void setOfferShortLabel(String offerShortLabel) {
		this.offerShortLabel = offerShortLabel;
	}

	public int getOfferSortValue() {
		return offerSortValue;
	}

	public void setOfferSortValue(int offerSortValue) {
		this.offerSortValue = offerSortValue;
	}

	public int getOfferSplits() {
		return offerSplits;
	}

	public void setOfferSplits(int offerSplits) {
		this.offerSplits = offerSplits;
	}

	public RaceMode getRaceMode() {
		return raceMode;
	}

	public void setRaceMode(RaceMode raceMode) {
		this.raceMode = raceMode;
	}

	public Set<ReportInfo> getReportInfos() {
		return reportInfos;
	}

	public void setReportInfos(Set<ReportInfo> reportInfos) {
		this.reportInfos = reportInfos;
	}
}