package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.Offer
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class OfferId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.Offer"); }
		catch(Exception e) {}
	}

	public int offerID;

	public OfferId() {
	}

	public OfferId(String str) {
		fromString(str);
	}

	public int getOfferID() {
		return offerID;
	}

	public void setOfferID(int offerID) {
		this.offerID = offerID;
	}

	public String toString() {
		return String.valueOf(offerID);
	}

	public int hashCode() {
		return offerID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		OfferId other = (OfferId) obj;
		return (offerID == other.offerID);
	}

	private void fromString(String str) {
		offerID = Integer.parseInt(str);
	}
}