package de.regatta_hd.aquarius.db;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="ProgressionRule")
@IdClass(de.regatta_hd.aquarius.db.ProgressionRuleId.class)
public class ProgressionRule {
	@Basic
	@Column(name="PR_Arg")
	private byte pRArg;

	@Basic
	@Column(name="PR_Option")
	private byte pROption;

	@Basic
	@Column(name="PR_Order")
	private short pROrder;

	@Basic
	@Column(name="PR_Type", nullable=false, length=1)
	private String pRType;

	@Id
	@Column(name="PR_ID", columnDefinition="int identity")
	private int prId;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="PR_RMLap_ID_FK", nullable=false)
	private RaceModeDetail raceModeDetail;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="PR_Src_Lap_ID_FK")
	private RaceModeDetail raceModeDetail2;


	public ProgressionRule() {
	}

	public ProgressionRule(int prId) {
		this.prId = prId;
	}

	public byte getpRArg() {
		return pRArg;
	}

	public void setpRArg(byte pRArg) {
		this.pRArg = pRArg;
	}

	public byte getpROption() {
		return pROption;
	}

	public void setpROption(byte pROption) {
		this.pROption = pROption;
	}

	public short getpROrder() {
		return pROrder;
	}

	public void setpROrder(short pROrder) {
		this.pROrder = pROrder;
	}

	public String getpRType() {
		return pRType;
	}

	public void setpRType(String pRType) {
		this.pRType = pRType;
	}

	public int getPrId() {
		return prId;
	}

	public void setPrId(int prId) {
		this.prId = prId;
	}

	public RaceModeDetail getRaceModeDetail() {
		return raceModeDetail;
	}

	public void setRaceModeDetail(RaceModeDetail raceModeDetail) {
		this.raceModeDetail = raceModeDetail;
	}

	public RaceModeDetail getRaceModeDetail2() {
		return raceModeDetail2;
	}

	public void setRaceModeDetail2(RaceModeDetail raceModeDetail2) {
		this.raceModeDetail2 = raceModeDetail2;
	}
}