package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.ProgressionRule
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class ProgressionRuleId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.ProgressionRule"); }
		catch(Exception e) {}
	}

	public int prId;

	public ProgressionRuleId() {
	}

	public ProgressionRuleId(String str) {
		fromString(str);
	}

	public int getPrId() {
		return prId;
	}

	public void setPrId(int prId) {
		this.prId = prId;
	}

	public String toString() {
		return String.valueOf(prId);
	}

	public int hashCode() {
		return prId;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		ProgressionRuleId other = (ProgressionRuleId) obj;
		return (prId == other.prId);
	}

	private void fromString(String str) {
		prId = Integer.parseInt(str);
	}
}