package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.RaceMode
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class RaceModeId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.RaceMode"); }
		catch(Exception e) {}
	}

	public int raceModeID;

	public RaceModeId() {
	}

	public RaceModeId(String str) {
		fromString(str);
	}

	public int getRaceModeID() {
		return raceModeID;
	}

	public void setRaceModeID(int raceModeID) {
		this.raceModeID = raceModeID;
	}

	public String toString() {
		return String.valueOf(raceModeID);
	}

	public int hashCode() {
		return raceModeID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		RaceModeId other = (RaceModeId) obj;
		return (raceModeID == other.raceModeID);
	}

	private void fromString(String str) {
		raceModeID = Integer.parseInt(str);
	}
}