package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.RaceModeRange
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class RaceModeRangeId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.RaceModeRange"); }
		catch(Exception e) {}
	}

	public int rMRangeID;

	public RaceModeRangeId() {
	}

	public RaceModeRangeId(String str) {
		fromString(str);
	}

	public int getRMRangeID() {
		return rMRangeID;
	}

	public void setRMRangeID(int rMRangeID) {
		this.rMRangeID = rMRangeID;
	}

	public String toString() {
		return String.valueOf(rMRangeID);
	}

	public int hashCode() {
		return rMRangeID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		RaceModeRangeId other = (RaceModeRangeId) obj;
		return (rMRangeID == other.rMRangeID);
	}

	private void fromString(String str) {
		rMRangeID = Integer.parseInt(str);
	}
}