package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="RaceMode_Detail")
@IdClass(de.regatta_hd.aquarius.db.RaceModeDetailId.class)
public class RaceModeDetail {
	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Comp.class, mappedBy="raceModeDetail", cascade=CascadeType.MERGE)
	private Set<Comp> comps = new HashSet<Comp>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.ProgressionRule.class, mappedBy="raceModeDetail", cascade=CascadeType.MERGE)
	private Set<ProgressionRule> progressionRules = new HashSet<ProgressionRule>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.ProgressionRule.class, mappedBy="raceModeDetail2", cascade=CascadeType.MERGE)
	private Set<ProgressionRule> progressionRules2 = new HashSet<ProgressionRule>();

	@Basic
	@Column(name="RMLap_Code", nullable=false, length=8)
	private String rMLapCode;

	@Id
	@Column(name="RMLap_ID", columnDefinition="int identity")
	private int rMLapID;

	@Basic
	@Column(name="RMLap_Label", nullable=false, length=8)
	private String rMLapLabel;

	@Basic
	@Column(name="RMLap_Number")
	private short rMLapNumber;

	@Basic
	@Column(name="RMLap_QRText", length=64)
	private String rMLapQRText;

	@Basic
	@Column(name="RMLap_Round")
	private int rMLapRound;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="RMLap_Range_ID_FK", nullable=false)
	private RaceModeRange raceModeRange;


	public RaceModeDetail() {
	}

	public RaceModeDetail(int rMLapID) {
		this.rMLapID = rMLapID;
	}

	public Set<Comp> getComps() {
		return comps;
	}

	public void setComps(Set<Comp> comps) {
		this.comps = comps;
	}

	public Set<ProgressionRule> getProgressionRules() {
		return progressionRules;
	}

	public void setProgressionRules(Set<ProgressionRule> progressionRules) {
		this.progressionRules = progressionRules;
	}

	public Set<ProgressionRule> getProgressionRules2() {
		return progressionRules2;
	}

	public void setProgressionRules2(Set<ProgressionRule> progressionRules2) {
		this.progressionRules2 = progressionRules2;
	}

	public String getrMLapCode() {
		return rMLapCode;
	}

	public void setrMLapCode(String rMLapCode) {
		this.rMLapCode = rMLapCode;
	}

	public int getrMLapID() {
		return rMLapID;
	}

	public void setrMLapID(int rMLapID) {
		this.rMLapID = rMLapID;
	}

	public String getrMLapLabel() {
		return rMLapLabel;
	}

	public void setrMLapLabel(String rMLapLabel) {
		this.rMLapLabel = rMLapLabel;
	}

	public short getrMLapNumber() {
		return rMLapNumber;
	}

	public void setrMLapNumber(short rMLapNumber) {
		this.rMLapNumber = rMLapNumber;
	}

	public String getrMLapQRText() {
		return rMLapQRText;
	}

	public void setrMLapQRText(String rMLapQRText) {
		this.rMLapQRText = rMLapQRText;
	}

	public int getrMLapRound() {
		return rMLapRound;
	}

	public void setrMLapRound(int rMLapRound) {
		this.rMLapRound = rMLapRound;
	}

	public RaceModeRange getRaceModeRange() {
		return raceModeRange;
	}

	public void setRaceModeRange(RaceModeRange raceModeRange) {
		this.raceModeRange = raceModeRange;
	}
}