package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="RaceMode_Range")
@IdClass(de.regatta_hd.aquarius.db.RaceModeRangeId.class)
public class RaceModeRange {
	@Basic
	@Column(name="RMRange_From")
	private int rMRangeFrom;

	@Id
	@Column(name="RMRange_ID", columnDefinition="int identity")
	private int rMRangeID;

	@Basic
	@Column(name="RMRange_To")
	private int rMRangeTo;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="RMRange_RM_ID_FK", nullable=false)
	private RaceMode raceMode;

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.RaceModeDetail.class, mappedBy="raceModeRange", cascade=CascadeType.MERGE)
	private Set<RaceModeDetail> raceModeDetails = new HashSet<RaceModeDetail>();


	public RaceModeRange() {
	}

	public RaceModeRange(int rMRangeID) {
		this.rMRangeID = rMRangeID;
	}

	public int getrMRangeFrom() {
		return rMRangeFrom;
	}

	public void setrMRangeFrom(int rMRangeFrom) {
		this.rMRangeFrom = rMRangeFrom;
	}

	public int getrMRangeID() {
		return rMRangeID;
	}

	public void setrMRangeID(int rMRangeID) {
		this.rMRangeID = rMRangeID;
	}

	public int getrMRangeTo() {
		return rMRangeTo;
	}

	public void setrMRangeTo(int rMRangeTo) {
		this.rMRangeTo = rMRangeTo;
	}

	public RaceMode getRaceMode() {
		return raceMode;
	}

	public void setRaceMode(RaceMode raceMode) {
		this.raceMode = raceMode;
	}

	public Set<RaceModeDetail> getRaceModeDetails() {
		return raceModeDetails;
	}

	public void setRaceModeDetails(Set<RaceModeDetail> raceModeDetails) {
		this.raceModeDetails = raceModeDetails;
	}
}