package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="Referee")
@IdClass(de.regatta_hd.aquarius.db.RefereeId.class)
public class Referee {
	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.CompReferee.class, mappedBy="referee", cascade=CascadeType.MERGE)
	private Set<CompReferee> compReferees = new HashSet<CompReferee>();

	@OneToMany(targetEntity=de.regatta_hd.aquarius.db.Event.class, mappedBy="referee", cascade=CascadeType.MERGE)
	private Set<Event> events = new HashSet<Event>();

	@ManyToMany(targetEntity=de.regatta_hd.aquarius.db.Event.class, mappedBy="referees", cascade=CascadeType.MERGE)
	private Set<Event> events2 = new HashSet<Event>();

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Referee_Nation_ID_FK")
	private Nation nation;

	@Basic
	@Column(name="Referee_City", length=32)
	private String refereeCity;

	@Basic
	@Column(name="Referee_ExternID")
	private int refereeExternID;

	@Basic
	@Column(name="Referee_FirstName", nullable=false, length=32)
	private String refereeFirstName;

	@Id
	@Column(name="Referee_ID", columnDefinition="int identity")
	private int refereeID;

	@Basic
	@Column(name="Referee_LastName", nullable=false, length=64)
	private String refereeLastName;

	@Basic
	@Column(name="Referee_LicenceState")
	private byte refereeLicenceState;


	public Referee() {
	}

	public Referee(int refereeID) {
		this.refereeID = refereeID;
	}

	public Set<CompReferee> getCompReferees() {
		return compReferees;
	}

	public void setCompReferees(Set<CompReferee> compReferees) {
		this.compReferees = compReferees;
	}

	public Set<Event> getEvents() {
		return events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	public Set<Event> getEvents2() {
		return events2;
	}

	public void setEvents2(Set<Event> events2) {
		this.events2 = events2;
	}

	public Nation getNation() {
		return nation;
	}

	public void setNation(Nation nation) {
		this.nation = nation;
	}

	public String getRefereeCity() {
		return refereeCity;
	}

	public void setRefereeCity(String refereeCity) {
		this.refereeCity = refereeCity;
	}

	public int getRefereeExternID() {
		return refereeExternID;
	}

	public void setRefereeExternID(int refereeExternID) {
		this.refereeExternID = refereeExternID;
	}

	public String getRefereeFirstName() {
		return refereeFirstName;
	}

	public void setRefereeFirstName(String refereeFirstName) {
		this.refereeFirstName = refereeFirstName;
	}

	public int getRefereeID() {
		return refereeID;
	}

	public void setRefereeID(int refereeID) {
		this.refereeID = refereeID;
	}

	public String getRefereeLastName() {
		return refereeLastName;
	}

	public void setRefereeLastName(String refereeLastName) {
		this.refereeLastName = refereeLastName;
	}

	public byte getRefereeLicenceState() {
		return refereeLicenceState;
	}

	public void setRefereeLicenceState(byte refereeLicenceState) {
		this.refereeLicenceState = refereeLicenceState;
	}
}