package de.regatta_hd.aquarius.db;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="ReportInfo")
@IdClass(de.regatta_hd.aquarius.db.ReportInfoId.class)
public class ReportInfo {
	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Report_Comp_ID_FK")
	private Comp comp;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Report_Event_ID_FK")
	private Event event;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="Report_Race_ID_FK")
	private Offer offer;

	@Basic
	@Column(name="Report_Backend", nullable=false, length=4)
	private String reportBackend;

	@Basic
	@Column(name="Report_Code", nullable=false, length=16)
	private String reportCode;

	@Basic
	@Column(name="Report_Date", columnDefinition="datetime")
	private Date reportDate;

	@Basic
	@Column(name="Report_Generated", columnDefinition="datetime")
	private Date reportGenerated;

	@Id
	@Column(name="ReportInfo_ID", columnDefinition="int identity")
	private int reportInfoID;

	@Basic
	@Column(name="Report_Round")
	private byte reportRound;

	@Basic
	@Column(name="Report_VersionMajor")
	private byte reportVersionMajor;

	@Basic
	@Column(name="Report_VersionMinor")
	private byte reportVersionMinor;


	public ReportInfo() {
	}

	public ReportInfo(int reportInfoID) {
		this.reportInfoID = reportInfoID;
	}

	public Comp getComp() {
		return comp;
	}

	public void setComp(Comp comp) {
		this.comp = comp;
	}

	public Event getEvent() {
		return event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Offer getOffer() {
		return offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	public String getReportBackend() {
		return reportBackend;
	}

	public void setReportBackend(String reportBackend) {
		this.reportBackend = reportBackend;
	}

	public String getReportCode() {
		return reportCode;
	}

	public void setReportCode(String reportCode) {
		this.reportCode = reportCode;
	}

	public Date getReportDate() {
		return reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	public Date getReportGenerated() {
		return reportGenerated;
	}

	public void setReportGenerated(Date reportGenerated) {
		this.reportGenerated = reportGenerated;
	}

	public int getReportInfoID() {
		return reportInfoID;
	}

	public void setReportInfoID(int reportInfoID) {
		this.reportInfoID = reportInfoID;
	}

	public byte getReportRound() {
		return reportRound;
	}

	public void setReportRound(byte reportRound) {
		this.reportRound = reportRound;
	}

	public byte getReportVersionMajor() {
		return reportVersionMajor;
	}

	public void setReportVersionMajor(byte reportVersionMajor) {
		this.reportVersionMajor = reportVersionMajor;
	}

	public byte getReportVersionMinor() {
		return reportVersionMinor;
	}

	public void setReportVersionMinor(byte reportVersionMinor) {
		this.reportVersionMinor = reportVersionMinor;
	}
}