package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.ReportInfo
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class ReportInfoId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.ReportInfo"); }
		catch(Exception e) {}
	}

	public int reportInfoID;

	public ReportInfoId() {
	}

	public ReportInfoId(String str) {
		fromString(str);
	}

	public int getReportInfoID() {
		return reportInfoID;
	}

	public void setReportInfoID(int reportInfoID) {
		this.reportInfoID = reportInfoID;
	}

	public String toString() {
		return String.valueOf(reportInfoID);
	}

	public int hashCode() {
		return reportInfoID;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		ReportInfoId other = (ReportInfoId) obj;
		return (reportInfoID == other.reportInfoID);
	}

	private void fromString(String str) {
		reportInfoID = Integer.parseInt(str);
	}
}