package de.regatta_hd.aquarius.db;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: de.regatta_hd.aquarius.db.Result
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class ResultId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("de.regatta_hd.aquarius.db.Result"); }
		catch(Exception e) {}
	}

	public int resultCEIDFK;
	public byte resultSplitNr;

	public ResultId() {
	}

	public ResultId(String str) {
		fromString(str);
	}

	public int getResultCEIDFK() {
		return resultCEIDFK;
	}

	public void setResultCEIDFK(int resultCEIDFK) {
		this.resultCEIDFK = resultCEIDFK;
	}

	public byte getResultSplitNr() {
		return resultSplitNr;
	}

	public void setResultSplitNr(byte resultSplitNr) {
		this.resultSplitNr = resultSplitNr;
	}

	public String toString() {
		return String.valueOf(resultCEIDFK)
			+ "::" + String.valueOf(resultSplitNr);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + resultCEIDFK;
		rs = rs * 37 + (int) resultSplitNr;
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		ResultId other = (ResultId) obj;
		return (resultCEIDFK == other.resultCEIDFK)
			&& (resultSplitNr == other.resultSplitNr);
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		resultCEIDFK = Integer.parseInt(str);
		str = toke.nextToken();
		resultSplitNr = Byte.parseByte(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}